package content.global.skill.construction

import core.game.world.map.Region
import core.game.world.map.RegionChunk
import core.game.world.map.RegionManager.forId

enum class RoomProperties(
    @JvmField val cost: Int,
    @JvmField val level: Int,
    val z: Int,
    @JvmField val chunkX: Int,
    @JvmField val chunkY: Int,
    private val configuration: Int,
    vararg hotspots: Hotspot,
) {
    PARLOUR(
        1000,
        1,
        0,
        0,
        7,
        Room.CHAMBER,
        Hotspot(BuildHotspot.BOOKCASE, 0, 1),
        Hotspot(BuildHotspot.WINDOW, 0, 2),
        Hotspot(BuildHotspot.WINDOW, 0, 5),
        Hotspot(BuildHotspot.WINDOW, 2, 0),
        Hotspot(BuildHotspot.WINDOW, 2, 7),
        Hotspot(BuildHotspot.WINDOW, 5, 0),
        Hotspot(BuildHotspot.WINDOW, 5, 7),
        Hotspot(BuildHotspot.WINDOW, 7, 2),
        Hotspot(BuildHotspot.WINDOW, 7, 5),
        Hotspot(BuildHotspot.CURTAINS, 2, 0),
        Hotspot(BuildHotspot.CURTAINS, 0, 2),
        Hotspot(BuildHotspot.CURTAINS, 0, 5),
        Hotspot(BuildHotspot.CURTAINS, 2, 7),
        Hotspot(BuildHotspot.CURTAINS, 5, 0),
        Hotspot(BuildHotspot.CURTAINS, 5, 7),
        Hotspot(BuildHotspot.CURTAINS, 7, 2),
        Hotspot(BuildHotspot.CURTAINS, 7, 5),
        Hotspot(BuildHotspot.RUG, 2, 2),
        Hotspot(BuildHotspot.RUG2, 2, 3),
        Hotspot(BuildHotspot.RUG2, 2, 4),
        Hotspot(BuildHotspot.RUG, 2, 5),
        Hotspot(BuildHotspot.RUG2, 3, 2),
        Hotspot(BuildHotspot.RUG3, 3, 3),
        Hotspot(BuildHotspot.RUG3, 3, 4),
        Hotspot(BuildHotspot.RUG2, 3, 5),
        Hotspot(BuildHotspot.RUG2, 4, 2),
        Hotspot(BuildHotspot.RUG3, 4, 3),
        Hotspot(BuildHotspot.RUG3, 4, 4),
        Hotspot(BuildHotspot.RUG2, 4, 5),
        Hotspot(BuildHotspot.RUG, 5, 2),
        Hotspot(BuildHotspot.RUG2, 5, 3),
        Hotspot(BuildHotspot.RUG2, 5, 4),
        Hotspot(BuildHotspot.RUG, 5, 5),
        Hotspot(BuildHotspot.CHAIRS_1, 2, 4),
        Hotspot(BuildHotspot.FIREPLACE, 3, 7, 4, 7),
        Hotspot(BuildHotspot.CHAIRS_3, 4, 3),
        Hotspot(BuildHotspot.CHAIRS_2, 5, 4),
        Hotspot(BuildHotspot.BOOKCASE, 7, 1),
    ),

    GARDEN(
        1000,
        1,
        0,
        0,
        1,
        Room.LAND,
        Hotspot(BuildHotspot.CENTREPIECE_1, 3, 3, 4, 4),
        Hotspot(BuildHotspot.BIG_PLANT_2, 0, 0, 1, 1),
        Hotspot(BuildHotspot.BIG_TREE_1, 1, 5, 2, 6),
        Hotspot(BuildHotspot.SMALL_PLANT_1, 3, 1),
        Hotspot(BuildHotspot.SMALL_PLANT_2, 4, 5),
        Hotspot(BuildHotspot.BIG_PLANT_1, 6, 0, 7, 1),
        Hotspot(BuildHotspot.TREE_1, 6, 6, 7, 7),
    ),

    KITCHEN(
        5000,
        5,
        0,
        2,
        7,
        Room.CHAMBER,
        Hotspot(BuildHotspot.CAT_BLANKET, 0, 0),
        Hotspot(BuildHotspot.WINDOW, 0, 2),
        Hotspot(BuildHotspot.WINDOW, 0, 5),
        Hotspot(BuildHotspot.WINDOW, 2, 0),
        Hotspot(BuildHotspot.WINDOW, 2, 7),
        Hotspot(BuildHotspot.WINDOW, 5, 0),
        Hotspot(BuildHotspot.WINDOW, 5, 7),
        Hotspot(BuildHotspot.WINDOW, 7, 2),
        Hotspot(BuildHotspot.WINDOW, 7, 5),
        Hotspot(BuildHotspot.BARRELS, 0, 6),
        Hotspot(BuildHotspot.KITCHEN_TABLE, 3, 3, 4, 4),
        Hotspot(BuildHotspot.STOVE, 3, 7, 4, 7),
        Hotspot(BuildHotspot.LARDER, 6, 0, 7, 1),
        Hotspot(BuildHotspot.SINK, 7, 3, 7, 4),
        Hotspot(BuildHotspot.SHELVES, 1, 7),
        Hotspot(BuildHotspot.SHELVES, 6, 7),
        Hotspot(BuildHotspot.SHELVES_2, 7, 6),
    ),

    DINING_ROOM(
        5000,
        10,
        0,
        4,
        7,
        Room.CHAMBER,
        Hotspot(BuildHotspot.FIREPLACE_DINING, 3, 7, 4, 7),
        Hotspot(BuildHotspot.WINDOW, 0, 2),
        Hotspot(BuildHotspot.WINDOW, 0, 5),
        Hotspot(BuildHotspot.WINDOW, 2, 0),
        Hotspot(BuildHotspot.WINDOW, 5, 0),
        Hotspot(BuildHotspot.WINDOW, 7, 2),
        Hotspot(BuildHotspot.WINDOW, 7, 5),
        Hotspot(BuildHotspot.DINING_CURTAINS, 0, 2),
        Hotspot(BuildHotspot.DINING_CURTAINS, 0, 5),
        Hotspot(BuildHotspot.DINING_CURTAINS, 2, 0),
        Hotspot(BuildHotspot.DINING_CURTAINS, 5, 0),
        Hotspot(BuildHotspot.DINING_CURTAINS, 7, 2),
        Hotspot(BuildHotspot.DINING_CURTAINS, 7, 5),
        Hotspot(BuildHotspot.WALL_DECORATION, 2, 7),
        Hotspot(BuildHotspot.WALL_DECORATION, 5, 7),
        Hotspot(BuildHotspot.DINING_BENCH_2, 2, 5),
        Hotspot(BuildHotspot.DINING_BENCH_2, 3, 5),
        Hotspot(BuildHotspot.DINING_BENCH_2, 4, 5),
        Hotspot(BuildHotspot.DINING_BENCH_2, 5, 5),
        Hotspot(BuildHotspot.DINING_BENCH_1, 2, 2),
        Hotspot(BuildHotspot.DINING_BENCH_1, 3, 2),
        Hotspot(BuildHotspot.DINING_BENCH_1, 4, 2),
        Hotspot(BuildHotspot.DINING_BENCH_1, 5, 2),
        Hotspot(BuildHotspot.ROPE_BELL_PULL, 0, 0),
        Hotspot(BuildHotspot.DINING_TABLE, 2, 3, 5, 4),
    ),

    WORKSHOP(
        10000,
        15,
        0,
        0,
        5,
        Room.CHAMBER,
        Hotspot(BuildHotspot.WORKBENCH, 3, 4, 4, 4),
        Hotspot(BuildHotspot.WINDOW, 0, 2),
        Hotspot(BuildHotspot.WINDOW, 0, 5),
        Hotspot(BuildHotspot.WINDOW, 2, 0),
        Hotspot(BuildHotspot.WINDOW, 5, 0),
        Hotspot(BuildHotspot.WINDOW, 7, 2),
        Hotspot(BuildHotspot.WINDOW, 7, 5),
        Hotspot(BuildHotspot.WINDOW, 2, 7),
        Hotspot(BuildHotspot.WINDOW, 5, 7),
        Hotspot(BuildHotspot.REPAIR, 7, 3, 7, 4),
        Hotspot(BuildHotspot.HERALDRY, 7, 6, 7, 7),
        Hotspot(BuildHotspot.CRAFTING, 0, 3, 0, 4),
        Hotspot(BuildHotspot.WORKBENCH, 3, 4),
        Hotspot(BuildHotspot.TOOL4, 7, 1),
        Hotspot(BuildHotspot.TOOL2, 6, 0),
        Hotspot(BuildHotspot.TOOL1, 1, 0),
        Hotspot(BuildHotspot.TOOL3, 0, 1),
        Hotspot(BuildHotspot.TOOL5, 0, 6),
    ),

    BEDROOM(
        10000,
        20,
        0,
        6,
        7,
        Room.CHAMBER,
        Hotspot(BuildHotspot.BED, 3, 6, 4, 7),
        Hotspot(BuildHotspot.FIREPLACE2, 7, 3, 7, 4),
        Hotspot(BuildHotspot.CLOCK, 7, 0),
        Hotspot(BuildHotspot.DRESSER, 0, 7, 1, 7),
        Hotspot(BuildHotspot.DRAWERS, 6, 7),
        Hotspot(BuildHotspot.WINDOW, 0, 2),
        Hotspot(BuildHotspot.WINDOW, 0, 5),
        Hotspot(BuildHotspot.WINDOW, 2, 0),
        Hotspot(BuildHotspot.WINDOW, 5, 0),
        Hotspot(BuildHotspot.WINDOW, 7, 2),
        Hotspot(BuildHotspot.WINDOW, 7, 5),
        Hotspot(BuildHotspot.WINDOW, 2, 7),
        Hotspot(BuildHotspot.WINDOW, 5, 7),
        Hotspot(BuildHotspot.BEDROOM_CURTAINS, 0, 2),
        Hotspot(BuildHotspot.BEDROOM_CURTAINS, 0, 5),
        Hotspot(BuildHotspot.BEDROOM_CURTAINS, 2, 0),
        Hotspot(BuildHotspot.BEDROOM_CURTAINS, 5, 0),
        Hotspot(BuildHotspot.BEDROOM_CURTAINS, 7, 2),
        Hotspot(BuildHotspot.BEDROOM_CURTAINS, 7, 5),
        Hotspot(BuildHotspot.BEDROOM_CURTAINS, 2, 7),
        Hotspot(BuildHotspot.BEDROOM_CURTAINS, 5, 7),
        Hotspot(BuildHotspot.BEDROOM_RUG, 2, 2),
        Hotspot(BuildHotspot.BEDROOM_RUG, 2, 3),
        Hotspot(BuildHotspot.BEDROOM_RUG, 3, 2),
        Hotspot(BuildHotspot.BEDROOM_RUG, 3, 3),
        Hotspot(BuildHotspot.BEDROOM_RUG, 4, 2),
        Hotspot(BuildHotspot.BEDROOM_RUG, 4, 3),
        Hotspot(BuildHotspot.BEDROOM_RUG, 5, 2),
        Hotspot(BuildHotspot.BEDROOM_RUG, 5, 3),
        Hotspot(BuildHotspot.BEDROOM_RUG2, 2, 1),
        Hotspot(BuildHotspot.BEDROOM_RUG2, 3, 1),
        Hotspot(BuildHotspot.BEDROOM_RUG2, 4, 1),
        Hotspot(BuildHotspot.BEDROOM_RUG2, 5, 1),
        Hotspot(BuildHotspot.BEDROOM_RUG2, 2, 4),
        Hotspot(BuildHotspot.BEDROOM_RUG2, 3, 4),
        Hotspot(BuildHotspot.BEDROOM_RUG2, 4, 4),
        Hotspot(BuildHotspot.BEDROOM_RUG2, 5, 4),
        Hotspot(BuildHotspot.BEDROOM_RUG2, 6, 2),
        Hotspot(BuildHotspot.BEDROOM_RUG2, 6, 3),
        Hotspot(BuildHotspot.BEDROOM_RUG2, 1, 2),
        Hotspot(BuildHotspot.BEDROOM_RUG2, 1, 3),
        Hotspot(BuildHotspot.BEDROOM_RUG2, 3, 2),
        Hotspot(BuildHotspot.BEDROOM_RUG2, 3, 5),
        Hotspot(BuildHotspot.BEDROOM_RUG2, 4, 5),
        Hotspot(BuildHotspot.BEDROOM_RUG2, 4, 2),
        Hotspot(BuildHotspot.BEDROOM_RUG3, 1, 1),
        Hotspot(BuildHotspot.BEDROOM_RUG3, 1, 4),
        Hotspot(BuildHotspot.BEDROOM_RUG3, 6, 1),
        Hotspot(BuildHotspot.BEDROOM_RUG3, 6, 4),
    ),

    SKILL_HALL(
        15000,
        25,
        0,
        1,
        6,
        Room.CHAMBER,
        Hotspot(BuildHotspot.STAIRWAYS, 3, 3, 4, 4),
        Hotspot(BuildHotspot.ARMOUR_SPACE, 2, 3),
        Hotspot(BuildHotspot.ARMOUR_SPACE2, 5, 3),
        Hotspot(BuildHotspot.HEAD_TROPHY, 6, 7),
        Hotspot(BuildHotspot.RUNE_CASE, 0, 6),
        Hotspot(BuildHotspot.FISHING_TROPHY, 1, 7),
        Hotspot(BuildHotspot.WINDOW, 0, 2),
        Hotspot(BuildHotspot.WINDOW, 0, 5),
        Hotspot(BuildHotspot.WINDOW, 2, 0),
        Hotspot(BuildHotspot.WINDOW, 5, 0),
        Hotspot(BuildHotspot.WINDOW, 7, 2),
        Hotspot(BuildHotspot.WINDOW, 7, 5),
        Hotspot(BuildHotspot.WINDOW, 2, 7),
        Hotspot(BuildHotspot.WINDOW, 5, 7),
        Hotspot(BuildHotspot.HALL_RUG, 2, 2),
        Hotspot(BuildHotspot.HALL_RUG, 3, 2),
        Hotspot(BuildHotspot.HALL_RUG, 4, 2),
        Hotspot(BuildHotspot.HALL_RUG, 5, 2),
        Hotspot(BuildHotspot.HALL_RUG, 2, 3),
        Hotspot(BuildHotspot.HALL_RUG, 3, 3),
        Hotspot(BuildHotspot.HALL_RUG, 4, 3),
        Hotspot(BuildHotspot.HALL_RUG, 5, 3),
        Hotspot(BuildHotspot.HALL_RUG, 2, 4),
        Hotspot(BuildHotspot.HALL_RUG, 3, 4),
        Hotspot(BuildHotspot.HALL_RUG, 4, 4),
        Hotspot(BuildHotspot.HALL_RUG, 5, 4),
        Hotspot(BuildHotspot.HALL_RUG, 2, 5),
        Hotspot(BuildHotspot.HALL_RUG, 3, 5),
        Hotspot(BuildHotspot.HALL_RUG, 4, 5),
        Hotspot(BuildHotspot.HALL_RUG, 5, 5),
        Hotspot(BuildHotspot.HALL_RUG2, 1, 2),
        Hotspot(BuildHotspot.HALL_RUG2, 1, 3),
        Hotspot(BuildHotspot.HALL_RUG2, 1, 4),
        Hotspot(BuildHotspot.HALL_RUG2, 1, 5),
        Hotspot(BuildHotspot.HALL_RUG2, 6, 2),
        Hotspot(BuildHotspot.HALL_RUG2, 6, 3),
        Hotspot(BuildHotspot.HALL_RUG2, 6, 4),
        Hotspot(BuildHotspot.HALL_RUG2, 6, 5),
        Hotspot(BuildHotspot.HALL_RUG2, 2, 1),
        Hotspot(BuildHotspot.HALL_RUG2, 3, 1),
        Hotspot(BuildHotspot.HALL_RUG2, 4, 1),
        Hotspot(BuildHotspot.HALL_RUG2, 5, 1),
        Hotspot(BuildHotspot.HALL_RUG2, 2, 6),
        Hotspot(BuildHotspot.HALL_RUG2, 3, 6),
        Hotspot(BuildHotspot.HALL_RUG2, 4, 6),
        Hotspot(BuildHotspot.HALL_RUG2, 5, 6),
        Hotspot(BuildHotspot.HALL_RUG3, 1, 1),
        Hotspot(BuildHotspot.HALL_RUG3, 1, 6),
        Hotspot(BuildHotspot.HALL_RUG3, 6, 1),
        Hotspot(BuildHotspot.HALL_RUG3, 6, 6),
    ),

    GAMES_ROOM(
        25000,
        30,
        0,
        5,
        4,
        Room.CHAMBER,
        Hotspot(BuildHotspot.RANGING_GAME, 1, 0),
        Hotspot(BuildHotspot.ATTACK_STONE, 2, 4),
        Hotspot(BuildHotspot.PRIZE_CHEST, 3, 7),
        Hotspot(BuildHotspot.ELEMENTAL_BALANCE, 5, 4),
        Hotspot(BuildHotspot.GAME_SPACE, 6, 0, 7, 1),
        Hotspot(BuildHotspot.WINDOW, 0, 2),
        Hotspot(BuildHotspot.WINDOW, 0, 5),
        Hotspot(BuildHotspot.WINDOW, 2, 0),
        Hotspot(BuildHotspot.WINDOW, 5, 0),
        Hotspot(BuildHotspot.WINDOW, 7, 2),
        Hotspot(BuildHotspot.WINDOW, 7, 5),
        Hotspot(BuildHotspot.WINDOW, 2, 7),
        Hotspot(BuildHotspot.WINDOW, 5, 7),
    ),

    COMBAT_ROOM(
        25000,
        32,
        0,
        3,
        4,
        Room.CHAMBER,
        Hotspot(BuildHotspot.STORAGE_SPACE, 3, 7),
        Hotspot(BuildHotspot.WALL_DECORATION2, 1, 7),
        Hotspot(BuildHotspot.WALL_DECORATION2, 6, 7),
        Hotspot(BuildHotspot.WINDOW, 0, 2),
        Hotspot(BuildHotspot.WINDOW, 0, 5),
        Hotspot(BuildHotspot.WINDOW, 2, 0),
        Hotspot(BuildHotspot.WINDOW, 5, 0),
        Hotspot(BuildHotspot.WINDOW, 7, 2),
        Hotspot(BuildHotspot.WINDOW, 7, 5),
        Hotspot(BuildHotspot.WINDOW, 2, 7),
        Hotspot(BuildHotspot.WINDOW, 5, 7),
        Hotspot(BuildHotspot.CR_CORNER, 6, 1),
        Hotspot(BuildHotspot.CR_CORNER2, 1, 1),
        Hotspot(BuildHotspot.CR_CORNER3, 1, 6),
        Hotspot(BuildHotspot.CR_CORNER4, 6, 6),
        Hotspot(BuildHotspot.CR_RING, 2, 1),
        Hotspot(BuildHotspot.CR_RING, 3, 1),
        Hotspot(BuildHotspot.CR_RING, 4, 1),
        Hotspot(BuildHotspot.CR_RING2, 5, 1),
        Hotspot(BuildHotspot.CR_RING, 1, 2),
        Hotspot(BuildHotspot.CR_RING, 1, 3),
        Hotspot(BuildHotspot.CR_RING, 1, 4),
        Hotspot(BuildHotspot.CR_RING3, 1, 5),
        Hotspot(BuildHotspot.CR_RING3, 2, 6),
        Hotspot(BuildHotspot.CR_RING4, 3, 6),
        Hotspot(BuildHotspot.CR_RING4, 4, 6),
        Hotspot(BuildHotspot.CR_RING4, 5, 6),
        Hotspot(BuildHotspot.CR_RING4, 6, 5),
        Hotspot(BuildHotspot.CR_RING, 6, 4),
        Hotspot(BuildHotspot.CR_RING, 6, 3),
        Hotspot(BuildHotspot.CR_RING2, 6, 2),
        Hotspot(BuildHotspot.CR_FLOOR7, 2, 2),
        Hotspot(BuildHotspot.CR_FLOOR4, 2, 3),
        Hotspot(BuildHotspot.CR_FLOOR4, 2, 4),
        Hotspot(BuildHotspot.CR_FLOOR3, 2, 5),
        Hotspot(BuildHotspot.CR_FLOOR6, 3, 2),
        Hotspot(BuildHotspot.CR_FLOOR5, 3, 3),
        Hotspot(BuildHotspot.CR_FLOOR5, 3, 4),
        Hotspot(BuildHotspot.CR_FLOOR, 3, 5),
        Hotspot(BuildHotspot.CR_FLOOR6, 4, 2),
        Hotspot(BuildHotspot.CR_FLOOR5, 4, 3),
        Hotspot(BuildHotspot.CR_FLOOR5, 4, 4),
        Hotspot(BuildHotspot.CR_FLOOR, 4, 5),
        Hotspot(BuildHotspot.CR_FLOOR8, 5, 2),
        Hotspot(BuildHotspot.CR_FLOOR4, 5, 3),
        Hotspot(BuildHotspot.CR_FLOOR4, 5, 4),
        Hotspot(BuildHotspot.CR_FLOOR2, 5, 5),
        Hotspot(BuildHotspot.CR_INVISIBLE_WALL2, 2, 4),
        Hotspot(BuildHotspot.CR_INVISIBLE_WALL, 3, 5),
        Hotspot(BuildHotspot.CR_INVISIBLE_WALL, 5, 3),
        Hotspot(BuildHotspot.CR_INVISIBLE_WALL, 4, 2),
    ),

    QUEST_HALL(
        25000,
        35,
        0,
        5,
        6,
        Room.CHAMBER,
        Hotspot(BuildHotspot.QUEST_STAIRWAYS, 3, 3, 4, 4),
        Hotspot(BuildHotspot.MAP, 7, 1),
        Hotspot(BuildHotspot.SWORD, 7, 6),
        Hotspot(BuildHotspot.LANDSCAPE, 6, 7),
        Hotspot(BuildHotspot.PORTRAIT, 1, 7),
        Hotspot(BuildHotspot.GUILD_TROPHY, 0, 6),
        Hotspot(BuildHotspot.BOOKCASE2, 0, 1),
        Hotspot(BuildHotspot.WINDOW, 0, 2),
        Hotspot(BuildHotspot.WINDOW, 0, 5),
        Hotspot(BuildHotspot.WINDOW, 2, 0),
        Hotspot(BuildHotspot.WINDOW, 5, 0),
        Hotspot(BuildHotspot.WINDOW, 7, 2),
        Hotspot(BuildHotspot.WINDOW, 7, 5),
        Hotspot(BuildHotspot.WINDOW, 2, 7),
        Hotspot(BuildHotspot.WINDOW, 5, 7),
        Hotspot(BuildHotspot.Q_HALL_RUG, 2, 2),
        Hotspot(BuildHotspot.Q_HALL_RUG, 3, 2),
        Hotspot(BuildHotspot.Q_HALL_RUG, 4, 2),
        Hotspot(BuildHotspot.Q_HALL_RUG, 5, 2),
        Hotspot(BuildHotspot.Q_HALL_RUG, 2, 3),
        Hotspot(BuildHotspot.Q_HALL_RUG, 3, 3),
        Hotspot(BuildHotspot.Q_HALL_RUG, 4, 3),
        Hotspot(BuildHotspot.Q_HALL_RUG, 5, 3),
        Hotspot(BuildHotspot.Q_HALL_RUG, 2, 4),
        Hotspot(BuildHotspot.Q_HALL_RUG, 3, 4),
        Hotspot(BuildHotspot.Q_HALL_RUG, 4, 4),
        Hotspot(BuildHotspot.Q_HALL_RUG, 5, 4),
        Hotspot(BuildHotspot.Q_HALL_RUG, 2, 5),
        Hotspot(BuildHotspot.Q_HALL_RUG, 3, 5),
        Hotspot(BuildHotspot.Q_HALL_RUG, 4, 5),
        Hotspot(BuildHotspot.Q_HALL_RUG, 5, 5),
        Hotspot(BuildHotspot.Q_HALL_RUG2, 1, 2),
        Hotspot(BuildHotspot.Q_HALL_RUG2, 1, 3),
        Hotspot(BuildHotspot.Q_HALL_RUG2, 1, 4),
        Hotspot(BuildHotspot.Q_HALL_RUG2, 1, 5),
        Hotspot(BuildHotspot.Q_HALL_RUG2, 6, 2),
        Hotspot(BuildHotspot.Q_HALL_RUG2, 6, 3),
        Hotspot(BuildHotspot.Q_HALL_RUG2, 6, 4),
        Hotspot(BuildHotspot.Q_HALL_RUG2, 6, 5),
        Hotspot(BuildHotspot.Q_HALL_RUG2, 2, 1),
        Hotspot(BuildHotspot.Q_HALL_RUG2, 3, 1),
        Hotspot(BuildHotspot.Q_HALL_RUG2, 4, 1),
        Hotspot(BuildHotspot.Q_HALL_RUG2, 5, 1),
        Hotspot(BuildHotspot.Q_HALL_RUG2, 2, 6),
        Hotspot(BuildHotspot.Q_HALL_RUG2, 3, 6),
        Hotspot(BuildHotspot.Q_HALL_RUG2, 4, 6),
        Hotspot(BuildHotspot.Q_HALL_RUG2, 5, 6),
        Hotspot(BuildHotspot.Q_HALL_RUG3, 1, 1),
        Hotspot(BuildHotspot.Q_HALL_RUG3, 1, 6),
        Hotspot(BuildHotspot.Q_HALL_RUG3, 6, 1),
        Hotspot(BuildHotspot.Q_HALL_RUG3, 6, 6),
    ),

    STUDY_ROOM(
        50000,
        40,
        0,
        4,
        5,
        Room.CHAMBER,
        Hotspot(BuildHotspot.GLOBE, 1, 4, 3, 6),
        Hotspot(BuildHotspot.LECTERN, 2, 2),
        Hotspot(BuildHotspot.CRYSTAL_BALL, 5, 2),
        Hotspot(BuildHotspot.BOOKCASE3, 3, 7, 3, 7),
        Hotspot(BuildHotspot.BOOKCASE3, 4, 7, 4, 7),
        Hotspot(BuildHotspot.WALL_CHART, 1, 7),
        Hotspot(BuildHotspot.WALL_CHART, 6, 7),
        Hotspot(BuildHotspot.WALL_CHART, 7, 1),
        Hotspot(BuildHotspot.WALL_CHART, 0, 1),
        Hotspot(BuildHotspot.TELESCOPE, 5, 7),
        Hotspot(BuildHotspot.WINDOW, 0, 2),
        Hotspot(BuildHotspot.WINDOW, 0, 5),
        Hotspot(BuildHotspot.WINDOW, 2, 0),
        Hotspot(BuildHotspot.WINDOW, 5, 0),
        Hotspot(BuildHotspot.WINDOW, 7, 2),
        Hotspot(BuildHotspot.WINDOW, 7, 5),
        Hotspot(BuildHotspot.WINDOW, 2, 7),
        Hotspot(BuildHotspot.WINDOW, 5, 7),
    ),

    COSTUME_ROOM(
        50000,
        42,
        0,
        6,
        1,
        Room.CHAMBER,
        Hotspot(BuildHotspot.WINDOW, 0, 2),
        Hotspot(BuildHotspot.WINDOW, 0, 5),
        Hotspot(BuildHotspot.WINDOW, 2, 0),
        Hotspot(BuildHotspot.WINDOW, 5, 0),
        Hotspot(BuildHotspot.WINDOW, 7, 2),
        Hotspot(BuildHotspot.WINDOW, 7, 5),
        Hotspot(BuildHotspot.TREASURE_CHEST, 0, 3, 0, 4),
        Hotspot(BuildHotspot.ARMOUR_CASE, 2, 7),
        Hotspot(BuildHotspot.MAGIC_WARDROBE, 3, 7, 5, 7),
        Hotspot(BuildHotspot.CAPE_RACK, 6, 6),
        Hotspot(BuildHotspot.TOY_BOX, 7, 3, 7, 4),
        Hotspot(BuildHotspot.COSTUME_BOX, 3, 3, 4, 4),
    ),

    CHAPEL(
        50000,
        45,
        0,
        2,
        5,
        Room.CHAMBER,
        Hotspot(BuildHotspot.ALTAR, 3, 5, 4, 5),
        Hotspot(BuildHotspot.STATUE, 7, 0),
        Hotspot(BuildHotspot.STATUE, 0, 0),
        Hotspot(BuildHotspot.ICON, 3, 7, 4, 7),
        Hotspot(BuildHotspot.MUSICAL, 7, 3, 7, 4),
        Hotspot(BuildHotspot.BURNERS, 1, 5),
        Hotspot(BuildHotspot.BURNERS, 6, 5),
        Hotspot(BuildHotspot.CHAPEL_RUG, 3, 1),
        Hotspot(BuildHotspot.CHAPEL_RUG, 4, 1),
        Hotspot(BuildHotspot.CHAPEL_RUG, 3, 2),
        Hotspot(BuildHotspot.CHAPEL_RUG, 4, 2),
        Hotspot(BuildHotspot.CHAPEL_RUG, 3, 3),
        Hotspot(BuildHotspot.CHAPEL_RUG, 4, 3),
        Hotspot(BuildHotspot.CHAPEL_RUG2, 3, 0),
        Hotspot(BuildHotspot.CHAPEL_RUG2, 4, 0),
        Hotspot(BuildHotspot.CHAPEL_RUG2, 3, 4),
        Hotspot(BuildHotspot.CHAPEL_RUG2, 4, 4),
        Hotspot(BuildHotspot.CHAPEL_WINDOW, 0, 2),
        Hotspot(BuildHotspot.CHAPEL_WINDOW, 0, 5),
        Hotspot(BuildHotspot.CHAPEL_WINDOW, 2, 7),
        Hotspot(BuildHotspot.CHAPEL_WINDOW, 5, 7),
        Hotspot(BuildHotspot.CHAPEL_WINDOW, 7, 5),
        Hotspot(BuildHotspot.CHAPEL_WINDOW, 7, 2),
    ),

    PORTAL_CHAMBER(
        100000,
        50,
        0,
        1,
        4,
        Room.CHAMBER,
        Hotspot(BuildHotspot.TELEPORT_FOCUS, 3, 3, 4, 4),
        Hotspot(BuildHotspot.PORTAL1, 0, 3, 0, 4),
        Hotspot(BuildHotspot.PORTAL2, 3, 7, 4, 7),
        Hotspot(BuildHotspot.PORTAL3, 7, 3, 7, 4),
        Hotspot(BuildHotspot.WINDOW, 0, 2),
        Hotspot(BuildHotspot.WINDOW, 0, 5),
        Hotspot(BuildHotspot.WINDOW, 2, 0),
        Hotspot(BuildHotspot.WINDOW, 5, 0),
        Hotspot(BuildHotspot.WINDOW, 7, 2),
        Hotspot(BuildHotspot.WINDOW, 7, 5),
        Hotspot(BuildHotspot.WINDOW, 2, 7),
        Hotspot(BuildHotspot.WINDOW, 5, 7),
    ),

    FORMAL_GARDEN(
        75000,
        55,
        0,
        2,
        1,
        Room.LAND,
        Hotspot(BuildHotspot.CENTREPIECE_2, 3, 3, 4, 4),
        Hotspot(BuildHotspot.FENCING, 0, 0),
        Hotspot(BuildHotspot.FENCING, 1, 0),
        Hotspot(BuildHotspot.FENCING, 2, 0),
        Hotspot(BuildHotspot.FENCING, 5, 0),
        Hotspot(BuildHotspot.FENCING, 6, 0),
        Hotspot(BuildHotspot.FENCING, 7, 0),
        Hotspot(BuildHotspot.FENCING, 7, 1),
        Hotspot(BuildHotspot.FENCING, 7, 2),
        Hotspot(BuildHotspot.FENCING, 7, 5),
        Hotspot(BuildHotspot.FENCING, 7, 6),
        Hotspot(BuildHotspot.FENCING, 7, 7),
        Hotspot(BuildHotspot.FENCING, 6, 7),
        Hotspot(BuildHotspot.FENCING, 5, 7),
        Hotspot(BuildHotspot.FENCING, 2, 7),
        Hotspot(BuildHotspot.FENCING, 1, 7),
        Hotspot(BuildHotspot.FENCING, 0, 7),
        Hotspot(BuildHotspot.FENCING, 0, 6),
        Hotspot(BuildHotspot.FENCING, 0, 5),
        Hotspot(BuildHotspot.FENCING, 0, 2),
        Hotspot(BuildHotspot.FENCING, 0, 1),
        Hotspot(BuildHotspot.HEDGE3, 0, 0),
        Hotspot(BuildHotspot.HEDGE2, 1, 0),
        Hotspot(BuildHotspot.HEDGE1, 2, 0),
        Hotspot(BuildHotspot.HEDGE1, 5, 0),
        Hotspot(BuildHotspot.HEDGE2, 6, 0),
        Hotspot(BuildHotspot.HEDGE3, 7, 0),
        Hotspot(BuildHotspot.HEDGE2, 7, 1),
        Hotspot(BuildHotspot.HEDGE1, 7, 2),
        Hotspot(BuildHotspot.HEDGE1, 7, 5),
        Hotspot(BuildHotspot.HEDGE2, 7, 6),
        Hotspot(BuildHotspot.HEDGE3, 7, 7),
        Hotspot(BuildHotspot.HEDGE2, 6, 7),
        Hotspot(BuildHotspot.HEDGE1, 5, 7),
        Hotspot(BuildHotspot.HEDGE1, 2, 7),
        Hotspot(BuildHotspot.HEDGE2, 1, 7),
        Hotspot(BuildHotspot.HEDGE3, 0, 7),
        Hotspot(BuildHotspot.HEDGE2, 0, 6),
        Hotspot(BuildHotspot.HEDGE1, 0, 5),
        Hotspot(BuildHotspot.HEDGE1, 0, 2),
        Hotspot(BuildHotspot.HEDGE2, 0, 1),
        Hotspot(BuildHotspot.SMALL_PLANT2, 2, 1),
        Hotspot(BuildHotspot.SMALL_PLANT2, 1, 2),
        Hotspot(BuildHotspot.SMALL_PLANT2, 5, 6),
        Hotspot(BuildHotspot.SMALL_PLANT2, 6, 5),
        Hotspot(BuildHotspot.SMALL_PLANT2, 2, 6),
        Hotspot(BuildHotspot.SMALL_PLANT2, 1, 5),
        Hotspot(BuildHotspot.BIG_PLANT2, 1, 1),
        Hotspot(BuildHotspot.BIG_PLANT2, 6, 6),
        Hotspot(BuildHotspot.BIG_PLANT2, 1, 6),
        Hotspot(BuildHotspot.SMALL_PLANT1, 5, 1),
        Hotspot(BuildHotspot.SMALL_PLANT1, 6, 2),
        Hotspot(BuildHotspot.SMALL_PLANT1, 1, 5),
        Hotspot(BuildHotspot.SMALL_PLANT1, 2, 1),
        Hotspot(BuildHotspot.SMALL_PLANT1, 2, 6),
        Hotspot(BuildHotspot.BIG_PLANT1, 1, 6),
        Hotspot(BuildHotspot.BIG_PLANT1, 1, 1),
        Hotspot(BuildHotspot.BIG_PLANT1, 6, 1),
    ),

    THRONE_ROOM(
        150000,
        60,
        0,
        6,
        5,
        Room.CHAMBER,
        Hotspot(BuildHotspot.WINDOW, 0, 2),
        Hotspot(BuildHotspot.WINDOW, 0, 5),
        Hotspot(BuildHotspot.WINDOW, 2, 0),
        Hotspot(BuildHotspot.WINDOW, 5, 0),
        Hotspot(BuildHotspot.WINDOW, 7, 2),
        Hotspot(BuildHotspot.WINDOW, 7, 5),
        Hotspot(BuildHotspot.WINDOW, 2, 7),
        Hotspot(BuildHotspot.WINDOW, 5, 7),
        Hotspot(BuildHotspot.THRONE, 3, 6),
        Hotspot(BuildHotspot.THRONE, 4, 6),
        Hotspot(BuildHotspot.LEVER, 6, 6),
        Hotspot(BuildHotspot.FLOOR, 3, 3),
        Hotspot(BuildHotspot.FLOOR, 3, 4),
        Hotspot(BuildHotspot.FLOOR, 4, 4),
        Hotspot(BuildHotspot.FLOOR, 4, 3),
        Hotspot(BuildHotspot.TRAPDOOR, 1, 6),
        Hotspot(BuildHotspot.SEATING1, 0, 0),
        Hotspot(BuildHotspot.SEATING1, 0, 1),
        Hotspot(BuildHotspot.SEATING1, 0, 2),
        Hotspot(BuildHotspot.SEATING1, 0, 3),
        Hotspot(BuildHotspot.SEATING1, 0, 4),
        Hotspot(BuildHotspot.SEATING1, 0, 5),
        Hotspot(BuildHotspot.SEATING2, 7, 0),
        Hotspot(BuildHotspot.SEATING2, 7, 1),
        Hotspot(BuildHotspot.SEATING2, 7, 2),
        Hotspot(BuildHotspot.SEATING2, 7, 3),
        Hotspot(BuildHotspot.SEATING2, 7, 4),
        Hotspot(BuildHotspot.SEATING2, 7, 5),
        Hotspot(BuildHotspot.DECORATION, 3, 7),
        Hotspot(BuildHotspot.DECORATION, 4, 7),
    ),

    OUBILETTE(
        150000,
        65,
        0,
        6,
        3,
        Room.DUNGEON,
        Hotspot(BuildHotspot.FLOOR_CORNER, 2, 2),
        Hotspot(BuildHotspot.FLOOR_CORNER, 5, 2),
        Hotspot(BuildHotspot.FLOOR_CORNER, 5, 5),
        Hotspot(BuildHotspot.FLOOR_CORNER, 2, 5),
        Hotspot(BuildHotspot.FLOOR_SIDE, 3, 2),
        Hotspot(BuildHotspot.FLOOR_SIDE, 4, 2),
        Hotspot(BuildHotspot.FLOOR_SIDE, 2, 3),
        Hotspot(BuildHotspot.FLOOR_SIDE, 2, 4),
        Hotspot(BuildHotspot.FLOOR_SIDE, 5, 3),
        Hotspot(BuildHotspot.FLOOR_SIDE, 5, 4),
        Hotspot(BuildHotspot.FLOOR_SIDE, 3, 5),
        Hotspot(BuildHotspot.FLOOR_SIDE, 4, 5),
        Hotspot(BuildHotspot.FLOOR_MID, 3, 3),
        Hotspot(BuildHotspot.FLOOR_MID, 3, 4),
        Hotspot(BuildHotspot.FLOOR_MID, 4, 3),
        Hotspot(BuildHotspot.FLOOR_MID, 4, 4),
        Hotspot(BuildHotspot.OUBLIETTE_FLOOR, 2, 2),
        Hotspot(BuildHotspot.OUBLIETTE_FLOOR, 5, 2),
        Hotspot(BuildHotspot.OUBLIETTE_FLOOR, 5, 5),
        Hotspot(BuildHotspot.OUBLIETTE_FLOOR, 2, 5),
        Hotspot(BuildHotspot.OUBLIETTE_FLOOR, 3, 2),
        Hotspot(BuildHotspot.OUBLIETTE_FLOOR, 4, 2),
        Hotspot(BuildHotspot.OUBLIETTE_FLOOR, 2, 3),
        Hotspot(BuildHotspot.OUBLIETTE_FLOOR, 2, 4),
        Hotspot(BuildHotspot.OUBLIETTE_FLOOR, 5, 3),
        Hotspot(BuildHotspot.OUBLIETTE_FLOOR, 5, 4),
        Hotspot(BuildHotspot.OUBLIETTE_FLOOR, 3, 5),
        Hotspot(BuildHotspot.OUBLIETTE_FLOOR, 4, 5),
        Hotspot(BuildHotspot.OUBLIETTE_FLOOR, 3, 3),
        Hotspot(BuildHotspot.OUBLIETTE_FLOOR, 3, 4),
        Hotspot(BuildHotspot.OUBLIETTE_FLOOR_1, 4, 3),
        Hotspot(BuildHotspot.OUBLIETTE_FLOOR, 4, 4),
        Hotspot(BuildHotspot.GUARD, 0, 0),
        Hotspot(BuildHotspot.DUNGEON_DECO, 0, 2),
        Hotspot(BuildHotspot.DUNGEON_DECO, 2, 7),
        Hotspot(BuildHotspot.DUNGEON_DECO, 7, 5),
        Hotspot(BuildHotspot.DUNGEON_DECO, 5, 0),
        Hotspot(BuildHotspot.OUBLIETTE_LIGHT, 2, 0),
        Hotspot(BuildHotspot.OUBLIETTE_LIGHT, 7, 2),
        Hotspot(BuildHotspot.OUBLIETTE_LIGHT, 5, 7),
        Hotspot(BuildHotspot.OUBLIETTE_LIGHT, 0, 5),
        Hotspot(BuildHotspot.LADDER, 1, 6),
        Hotspot(BuildHotspot.PRISON, 2, 2),
        Hotspot(BuildHotspot.PRISON, 2, 5),
        Hotspot(BuildHotspot.PRISON, 2, 3),
        Hotspot(BuildHotspot.PRISON, 2, 4),
        Hotspot(BuildHotspot.PRISON, 5, 2),
        Hotspot(BuildHotspot.PRISON, 5, 5),
        Hotspot(BuildHotspot.PRISON, 3, 2),
        Hotspot(BuildHotspot.PRISON, 4, 2),
        Hotspot(BuildHotspot.PRISON, 5, 3),
        Hotspot(BuildHotspot.PRISON, 5, 4),
        Hotspot(BuildHotspot.PRISON, 4, 5),
        Hotspot(BuildHotspot.PRISON_DOOR, 3, 5),
    ),

    DUNGEON_CORRIDOR(
        7500,
        70,
        0,
        4,
        3,
        Room.DUNGEON,
        Hotspot(BuildHotspot.DUNGEON_DOOR_RIGHT, 3, 1),
        Hotspot(BuildHotspot.DUNGEON_DOOR_LEFT, 4, 1),
        Hotspot(BuildHotspot.DUNGEON_DOOR_LEFT2, 3, 6),
        Hotspot(BuildHotspot.DUNGEON_DOOR_RIGHT2, 4, 6),
        Hotspot(BuildHotspot.DUNGEON_LIGHT, 3, 1),
        Hotspot(BuildHotspot.DUNGEON_LIGHT, 4, 1),
        Hotspot(BuildHotspot.DUNGEON_TRAP2, 3, 2),
        Hotspot(BuildHotspot.DUNGEON_TRAP2, 4, 2),
        Hotspot(BuildHotspot.DUNGEON_GUARD, 3, 3),
        Hotspot(BuildHotspot.DUNGEON_DECO, 4, 3),
        Hotspot(BuildHotspot.DUNGEON_DECO, 3, 4),
        Hotspot(BuildHotspot.DUNGEON_TRAP, 3, 5),
        Hotspot(BuildHotspot.DUNGEON_TRAP, 4, 5),
        Hotspot(BuildHotspot.DUNGEON_LIGHT, 3, 6),
        Hotspot(BuildHotspot.DUNGEON_LIGHT, 4, 6),
    ),

    DUNGEON_JUNCTION(
        7500,
        70,
        0,
        0,
        3,
        Room.DUNGEON,
        Hotspot(BuildHotspot.DUNGEON_DOOR_RIGHT, 3, 1),
        Hotspot(BuildHotspot.DUNGEON_DOOR_LEFT, 4, 1),
        Hotspot(BuildHotspot.DUNGEON_DOOR_LEFT2, 3, 6),
        Hotspot(BuildHotspot.DUNGEON_DOOR_RIGHT2, 4, 6),
        Hotspot(BuildHotspot.DUNGEON_LIGHT, 3, 1),
        Hotspot(BuildHotspot.DUNGEON_TRAP2, 3, 2),
        Hotspot(BuildHotspot.DUNGEON_TRAP2, 4, 2),
        Hotspot(BuildHotspot.DUNGEON_GUARD, 3, 3),
        Hotspot(BuildHotspot.DUNGEON_TRAP, 3, 5),
        Hotspot(BuildHotspot.DUNGEON_TRAP, 4, 5),
        Hotspot(BuildHotspot.DUNGEON_LIGHT, 4, 6),
        Hotspot(BuildHotspot.DUNGEON_DECO, 1, 3),
        Hotspot(BuildHotspot.DUNGEON_DECO, 6, 4),
        Hotspot(BuildHotspot.DUNGEON_LIGHT, 1, 4),
        Hotspot(BuildHotspot.DUNGEON_LIGHT, 6, 3),
    ),

    DUNGEON_STAIRS(
        7500,
        70,
        0,
        2,
        3,
        Room.DUNGEON,
        Hotspot(BuildHotspot.STAIRWAYS_DUNGEON, 3, 3),
        Hotspot(BuildHotspot.HALL_RUG, 3, 3),
        Hotspot(BuildHotspot.HALL_RUG, 4, 3),
        Hotspot(BuildHotspot.HALL_RUG, 3, 4),
        Hotspot(BuildHotspot.HALL_RUG, 4, 4),
        Hotspot(BuildHotspot.HALL_RUG2, 2, 3),
        Hotspot(BuildHotspot.HALL_RUG2, 2, 4),
        Hotspot(BuildHotspot.HALL_RUG2, 5, 3),
        Hotspot(BuildHotspot.HALL_RUG2, 5, 4),
        Hotspot(BuildHotspot.HALL_RUG2, 3, 2),
        Hotspot(BuildHotspot.HALL_RUG2, 4, 2),
        Hotspot(BuildHotspot.HALL_RUG2, 3, 5),
        Hotspot(BuildHotspot.HALL_RUG2, 4, 5),
        Hotspot(BuildHotspot.HALL_RUG3, 2, 2),
        Hotspot(BuildHotspot.HALL_RUG3, 2, 5),
        Hotspot(BuildHotspot.HALL_RUG3, 5, 2),
        Hotspot(BuildHotspot.HALL_RUG3, 5, 5),
        Hotspot(BuildHotspot.DUNGEON_DOOR_RIGHT, 3, 1),
        Hotspot(BuildHotspot.DUNGEON_DOOR_LEFT, 4, 1),
        Hotspot(BuildHotspot.DUNGEON_DOOR_LEFT2, 3, 6),
        Hotspot(BuildHotspot.DUNGEON_DOOR_RIGHT2, 4, 6),
        Hotspot(BuildHotspot.DUNGEON_LIGHT2, 2, 1),
        Hotspot(BuildHotspot.DUNGEON_LIGHT2, 5, 1),
        Hotspot(BuildHotspot.DUNGEON_LIGHT2, 2, 6),
        Hotspot(BuildHotspot.DUNGEON_LIGHT2, 5, 6),
        Hotspot(BuildHotspot.DUNGEON_GUARD3, 1, 1),
        Hotspot(BuildHotspot.DUNGEON_GUARD2, 5, 5),
        Hotspot(BuildHotspot.DUNGEON_DECO, 6, 1),
        Hotspot(BuildHotspot.DUNGEON_DECO, 1, 6),
    ),

    DUNGEON_PIT(
        10000,
        70,
        0,
        5,
        2,
        Room.DUNGEON,
        Hotspot(BuildHotspot.DUNGEON_DOOR_RIGHT3, 3, 1),
        Hotspot(BuildHotspot.DUNGEON_DOOR_LEFT3, 4, 1),
        Hotspot(BuildHotspot.DUNGEON_DOOR_LEFT3, 3, 6),
        Hotspot(BuildHotspot.DUNGEON_DOOR_RIGHT3, 4, 6),
        Hotspot(BuildHotspot.DUNGEON_DOOR_RIGHT3, 1, 4),
        Hotspot(BuildHotspot.DUNGEON_DOOR_LEFT3, 1, 3),
        Hotspot(BuildHotspot.DUNGEON_DOOR_LEFT3, 6, 4),
        Hotspot(BuildHotspot.DUNGEON_DOOR_RIGHT3, 6, 3),
        Hotspot(BuildHotspot.DUNGEON_DECO, 5, 1),
        Hotspot(BuildHotspot.DUNGEON_DECO, 1, 6),
        Hotspot(BuildHotspot.DUNGEON_LIGHT2, 2, 1),
        Hotspot(BuildHotspot.DUNGEON_LIGHT, 2, 6),
        Hotspot(BuildHotspot.DUNGEON_LIGHT, 5, 1),
        Hotspot(BuildHotspot.DUNGEON_LIGHT2, 5, 6),
        Hotspot(BuildHotspot.DUNGEON_LIGHT, 1, 2),
        Hotspot(BuildHotspot.DUNGEON_LIGHT2, 1, 5),
        Hotspot(BuildHotspot.DUNGEON_LIGHT2, 6, 2),
        Hotspot(BuildHotspot.DUNGEON_LIGHT, 6, 5),
        Hotspot(BuildHotspot.DUNGEON_PIT_GUARD, 3, 3),
    ),

    TREASURE_ROOM(
        250000,
        75,
        0,
        7,
        4,
        Room.DUNGEON,
        Hotspot(BuildHotspot.DUNGEON_DOOR_RIGHT2, 3, 1),
        Hotspot(BuildHotspot.DUNGEON_DOOR_LEFT2, 4, 1),
        Hotspot(BuildHotspot.DUNGEON_LIGHT, 2, 1),
        Hotspot(BuildHotspot.DUNGEON_LIGHT, 5, 1),
        Hotspot(BuildHotspot.DUNGEON_LIGHT, 1, 5),
        Hotspot(BuildHotspot.DUNGEON_LIGHT, 6, 5),
        Hotspot(BuildHotspot.DUNGEON_DECO, 1, 2),
        Hotspot(BuildHotspot.DUNGEON_DECO, 6, 2),
        Hotspot(BuildHotspot.MONSTER, 3, 3),
        Hotspot(BuildHotspot.TREASURE_CHEST1, 2, 6),
        Hotspot(BuildHotspot.WALL_DECORATION1, 3, 6),
        Hotspot(BuildHotspot.WALL_DECORATION1, 4, 6),
    ),

    ROOF_2_EXIT(0, 0, 0, 1, 2, Room.ROOF),

    ROOF_3_EXIT(0, 0, 0, 3, 2, Room.ROOF),

    ROOF_4_EXIT(0, 0, 0, 5, 2, Room.ROOF),

    SKILL_HALL_2(
        0,
        25,
        0,
        3,
        6,
        Room.CHAMBER,
        Hotspot(BuildHotspot.STAIRS_DOWN, 3, 3),
        Hotspot(BuildHotspot.ARMOUR_SPACE, 2, 3),
        Hotspot(BuildHotspot.ARMOUR_SPACE2, 5, 3),
        Hotspot(BuildHotspot.HEAD_TROPHY, 6, 7),
        Hotspot(BuildHotspot.RUNE_CASE, 0, 6),
        Hotspot(BuildHotspot.FISHING_TROPHY, 1, 7),
        Hotspot(BuildHotspot.WINDOW, 0, 2),
        Hotspot(BuildHotspot.WINDOW, 0, 5),
        Hotspot(BuildHotspot.WINDOW, 2, 0),
        Hotspot(BuildHotspot.WINDOW, 5, 0),
        Hotspot(BuildHotspot.WINDOW, 7, 2),
        Hotspot(BuildHotspot.WINDOW, 7, 5),
        Hotspot(BuildHotspot.WINDOW, 2, 7),
        Hotspot(BuildHotspot.WINDOW, 5, 7),
        Hotspot(BuildHotspot.HALL_RUG, 2, 2),
        Hotspot(BuildHotspot.HALL_RUG, 3, 2),
        Hotspot(BuildHotspot.HALL_RUG, 4, 2),
        Hotspot(BuildHotspot.HALL_RUG, 5, 2),
        Hotspot(BuildHotspot.HALL_RUG, 2, 3),
        Hotspot(BuildHotspot.HALL_RUG, 3, 3),
        Hotspot(BuildHotspot.HALL_RUG, 4, 3),
        Hotspot(BuildHotspot.HALL_RUG, 5, 3),
        Hotspot(BuildHotspot.HALL_RUG, 2, 4),
        Hotspot(BuildHotspot.HALL_RUG, 3, 4),
        Hotspot(BuildHotspot.HALL_RUG, 4, 4),
        Hotspot(BuildHotspot.HALL_RUG, 5, 4),
        Hotspot(BuildHotspot.HALL_RUG, 2, 5),
        Hotspot(BuildHotspot.HALL_RUG, 3, 5),
        Hotspot(BuildHotspot.HALL_RUG, 4, 5),
        Hotspot(BuildHotspot.HALL_RUG, 5, 5),
        Hotspot(BuildHotspot.HALL_RUG2, 1, 2),
        Hotspot(BuildHotspot.HALL_RUG2, 1, 3),
        Hotspot(BuildHotspot.HALL_RUG2, 1, 4),
        Hotspot(BuildHotspot.HALL_RUG2, 1, 5),
        Hotspot(BuildHotspot.HALL_RUG2, 6, 2),
        Hotspot(BuildHotspot.HALL_RUG2, 6, 3),
        Hotspot(BuildHotspot.HALL_RUG2, 6, 4),
        Hotspot(BuildHotspot.HALL_RUG2, 6, 5),
        Hotspot(BuildHotspot.HALL_RUG2, 2, 1),
        Hotspot(BuildHotspot.HALL_RUG2, 3, 1),
        Hotspot(BuildHotspot.HALL_RUG2, 4, 1),
        Hotspot(BuildHotspot.HALL_RUG2, 5, 1),
        Hotspot(BuildHotspot.HALL_RUG2, 2, 6),
        Hotspot(BuildHotspot.HALL_RUG2, 3, 6),
        Hotspot(BuildHotspot.HALL_RUG2, 4, 6),
        Hotspot(BuildHotspot.HALL_RUG2, 5, 6),
        Hotspot(BuildHotspot.HALL_RUG3, 1, 1),
        Hotspot(BuildHotspot.HALL_RUG3, 1, 6),
        Hotspot(BuildHotspot.HALL_RUG3, 6, 1),
        Hotspot(BuildHotspot.HALL_RUG3, 6, 6),
    ),

    QUEST_HALL_2(
        25000,
        35,
        0,
        7,
        6,
        Room.CHAMBER,
        Hotspot(BuildHotspot.STAIRS_DOWN2, 3, 3),
        Hotspot(BuildHotspot.MAP, 7, 1),
        Hotspot(BuildHotspot.SWORD, 7, 6),
        Hotspot(BuildHotspot.LANDSCAPE, 6, 7),
        Hotspot(BuildHotspot.PORTRAIT, 1, 7),
        Hotspot(BuildHotspot.GUILD_TROPHY, 0, 6),
        Hotspot(BuildHotspot.BOOKCASE2, 0, 1),
        Hotspot(BuildHotspot.WINDOW, 0, 2),
        Hotspot(BuildHotspot.WINDOW, 0, 5),
        Hotspot(BuildHotspot.WINDOW, 2, 0),
        Hotspot(BuildHotspot.WINDOW, 5, 0),
        Hotspot(BuildHotspot.WINDOW, 7, 2),
        Hotspot(BuildHotspot.WINDOW, 7, 5),
        Hotspot(BuildHotspot.WINDOW, 2, 7),
        Hotspot(BuildHotspot.WINDOW, 5, 7),
        Hotspot(BuildHotspot.Q_HALL_RUG, 2, 2),
        Hotspot(BuildHotspot.Q_HALL_RUG, 3, 2),
        Hotspot(BuildHotspot.Q_HALL_RUG, 4, 2),
        Hotspot(BuildHotspot.Q_HALL_RUG, 5, 2),
        Hotspot(BuildHotspot.Q_HALL_RUG, 2, 3),
        Hotspot(BuildHotspot.Q_HALL_RUG, 3, 3),
        Hotspot(BuildHotspot.Q_HALL_RUG, 4, 3),
        Hotspot(BuildHotspot.Q_HALL_RUG, 5, 3),
        Hotspot(BuildHotspot.Q_HALL_RUG, 2, 4),
        Hotspot(BuildHotspot.Q_HALL_RUG, 3, 4),
        Hotspot(BuildHotspot.Q_HALL_RUG, 4, 4),
        Hotspot(BuildHotspot.Q_HALL_RUG, 5, 4),
        Hotspot(BuildHotspot.Q_HALL_RUG, 2, 5),
        Hotspot(BuildHotspot.Q_HALL_RUG, 3, 5),
        Hotspot(BuildHotspot.Q_HALL_RUG, 4, 5),
        Hotspot(BuildHotspot.Q_HALL_RUG, 5, 5),
        Hotspot(BuildHotspot.Q_HALL_RUG2, 1, 2),
        Hotspot(BuildHotspot.Q_HALL_RUG2, 1, 3),
        Hotspot(BuildHotspot.Q_HALL_RUG2, 1, 4),
        Hotspot(BuildHotspot.Q_HALL_RUG2, 1, 5),
        Hotspot(BuildHotspot.Q_HALL_RUG2, 6, 2),
        Hotspot(BuildHotspot.Q_HALL_RUG2, 6, 3),
        Hotspot(BuildHotspot.Q_HALL_RUG2, 6, 4),
        Hotspot(BuildHotspot.Q_HALL_RUG2, 6, 5),
        Hotspot(BuildHotspot.Q_HALL_RUG2, 2, 1),
        Hotspot(BuildHotspot.Q_HALL_RUG2, 3, 1),
        Hotspot(BuildHotspot.Q_HALL_RUG2, 4, 1),
        Hotspot(BuildHotspot.Q_HALL_RUG2, 5, 1),
        Hotspot(BuildHotspot.Q_HALL_RUG2, 2, 6),
        Hotspot(BuildHotspot.Q_HALL_RUG2, 3, 6),
        Hotspot(BuildHotspot.Q_HALL_RUG2, 4, 6),
        Hotspot(BuildHotspot.Q_HALL_RUG2, 5, 6),
        Hotspot(BuildHotspot.Q_HALL_RUG3, 1, 1),
        Hotspot(BuildHotspot.Q_HALL_RUG3, 1, 6),
        Hotspot(BuildHotspot.Q_HALL_RUG3, 6, 1),
        Hotspot(BuildHotspot.Q_HALL_RUG3, 6, 6),
    ),
    ;

    companion object {
        val name: String = ""

            get() = field.lowercase().replace("_".toRegex(), " ").replace("\\d".toRegex(), "")
    }

    @JvmField
    val hotspots: Array<Hotspot> = hotspots as Array<Hotspot>

    val exits: BooleanArray

        get() {
            val region = forId(7503)
            Region.load(region, true)
            val chunk = region.planes[0].getRegionChunk(chunkX, chunkY)
            return booleanArrayOf(
                isExit(chunk, 7, 3),
                isExit(chunk, 3, 0),
                isExit(chunk, 0, 3),
                isExit(chunk, 3, 7),
            )
        }

    private fun isExit(
        chunk: RegionChunk,
        x: Int,
        y: Int,
    ): Boolean {
        for (`object` in chunk.getObjects(x, y)) {
            if (`object` != null && (`object`.id == 15313 || `object`.id == 15314 || `object`.id == 15317)) {
                return true
            }
        }
        return false
    }

    val isChamber: Boolean

        get() = !isLand && !isRoof

    val isLand: Boolean

        get() = (configuration and Room.LAND) != 0

    val isRoof: Boolean

        get() = (configuration and Room.ROOF) != 0

    val isDungeon: Boolean

        get() = (configuration and Room.DUNGEON) != 0
}
