package content.region.kandarin.quest.phoenix.book

import content.global.handlers.iface.BookInterface
import content.global.handlers.iface.BookLine
import content.global.handlers.iface.Page
import content.global.handlers.iface.PageSet
import core.game.interaction.IntType
import core.game.interaction.InteractionListener
import core.game.node.entity.player.Player
import org.rs.consts.Scenery

class PhoenixBook : InteractionListener {
    companion object {
        private const val TITLE = "The Phoenix"
        private val CONTENTS =
            arrayOf(
                PageSet(
                    Page(
                        BookLine("Foreword", 55),
                        BookLine("", 56),
                        BookLine("I have devoted much of", 57),
                        BookLine("my life to the study", 58),
                        BookLine("of this wondrous", 59),
                        BookLine("creature: the firebird", 60),
                        BookLine("of legend, the phoenix.", 61),
                        BookLine("I placed this book and", 62),
                        BookLine("the shrine it rests on", 63),
                        BookLine("in the phoenix's roost,", 64),
                        BookLine("shortly after it departed", 65),
                    ),
                    Page(
                        BookLine("on one of its many long", 66),
                        BookLine("absences of its lair.", 67),
                        BookLine("I will no doubt be", 68),
                        BookLine("continuing my research", 69),
                        BookLine("until the phoenix returns", 70),
                        BookLine("from its rebirth.", 71),
                        BookLine("Unfortunately, based on", 72),
                        BookLine("my research, this event", 73),
                        BookLine("will not occur until I", 74),
                        BookLine("am fully five decades", 75),
                        BookLine("older, and will no doubt", 76),
                    ),
                ),
                PageSet(
                    Page(
                        BookLine("have became a frail", 55),
                        BookLine("old man, unable to travel", 56),
                        BookLine("and see the event I", 57),
                        BookLine("have waited a lifetime", 58),
                        BookLine("to witness.", 59),
                        BookLine("I leave these records of", 60),
                        BookLine("my findings inside the", 61),
                        BookLine("phoenix's lair in the", 62),
                        BookLine("fond hope that you, dear", 63),
                        BookLine("reader, will read them,", 64),
                        BookLine("and come to understand", 65),
                    ),
                    Page(
                        BookLine("and admire the phoenix", 66),
                        BookLine("as I do and will all my", 67),
                        BookLine("life. Strength through", 68),
                        BookLine("balance", 69),
                        BookLine("", 70),
                        BookLine("", 71),
                        BookLine("Brian Twitcher", 72),
                        BookLine("", 73),
                        BookLine("The Phoenix", 74),
                        BookLine("", 75),
                        BookLine("The phoenix is a large", 76),
                    ),
                ),
                PageSet(
                    Page(
                        BookLine("avian creature. In terms", 55),
                        BookLine("of physical appearance", 56),
                        BookLine("its similar to a very", 57),
                        BookLine("large eagle, only with", 58),
                        BookLine("a fiery feathers almost", 59),
                        BookLine("all over, and a crest", 60),
                        BookLine("atop its head The only", 61),
                        BookLine("part of it that is not", 62),
                        BookLine("fiery oranges and red", 63),
                        BookLine("is its tail - its long,", 64),
                        BookLine("beautiful tail. The", 65),
                    ),
                    Page(
                        BookLine("magnificent tail", 66),
                        BookLine("feathers are a burning", 67),
                        BookLine("red towards the vase,", 68),
                        BookLine("and the colours grow", 69),
                        BookLine("gradually cooler towards", 70),
                        BookLine("the tips of its feathers,", 71),
                        BookLine("flowing to red to orange", 72),
                        BookLine("to yellow to green to a", 73),
                        BookLine("cool blue. The Phoenix", 74),
                        BookLine("is truly a magnificent", 75),
                        BookLine("sight to behold.", 76),
                    ),
                ),
                PageSet(
                    Page(
                        BookLine("", 55),
                        BookLine("My knowledge of the", 56),
                        BookLine("creature is little more", 57),
                        BookLine("than the observations", 58),
                        BookLine("of its behaviour, I", 59),
                        BookLine("kept myself concealed", 60),
                        BookLine("during my research,", 61),
                        BookLine("partially to avoid", 62),
                        BookLine("startling or upsetting", 63),
                        BookLine("the phoenix, but mostly", 64),
                        BookLine("out of a human fear of", 65),
                    ),
                    Page(
                        BookLine("death after witnessing", 66),
                        BookLine("some of its powerful", 67),
                        BookLine("magicks.", 68),
                        BookLine("", 69),
                        BookLine("The phoenix spend most", 70),
                        BookLine("of the time away from", 71),
                        BookLine("its lair (one of the", 72),
                        BookLine("main reasons I have", 73),
                        BookLine("been able to examine", 74),
                        BookLine("it roost chambers as", 75),
                        BookLine("much as I have!) and", 76),
                    ),
                ),
                PageSet(
                    Page(
                        BookLine("seems to return when", 55),
                        BookLine("there is a abnormal", 56),
                        BookLine("occurrence or problem", 57),
                        BookLine("within the lair. I", 58),
                        BookLine("have a theory as to", 59),
                        BookLine("how the phoenix does", 60),
                        BookLine("this, I shall explain", 61),
                        BookLine("later on this book.", 62),
                        BookLine("", 63),
                        BookLine("The phoenix's", 64),
                        BookLine("magicks include", 65),
                    ),
                    Page(
                        BookLine("the incomprehensible", 66),
                        BookLine("ability to revive the", 67),
                        BookLine("dead. Creatures it", 68),
                        BookLine("revives became servants", 69),
                        BookLine("of the phoenix, and", 70),
                        BookLine("spend their days in", 71),
                        BookLine("its lair. These are", 72),
                        BookLine("described in the next", 73),
                        BookLine("section, 'The Reborn'.", 74),
                        BookLine("", 75),
                        BookLine("The magic it has over", 76),
                    ),
                ),
                PageSet(
                    Page(
                        BookLine("life and death,", 55),
                        BookLine("coupled with evidence", 56),
                        BookLine("'liberated' from the", 57),
                        BookLine("phoenix's roost, lead", 58),
                        BookLine("me to believe that the", 59),
                        BookLine("phoenix is an ancient", 60),
                        BookLine("creature to whom the", 61),
                        BookLine("laws of life and death", 62),
                        BookLine("do not apply.", 63),
                        BookLine("", 64),
                        BookLine("I discovered several", 65),
                    ),
                    Page(
                        BookLine("items in the phoenix's", 66),
                        BookLine("roost that looked out", 67),
                        BookLine("of place, and took", 68),
                        BookLine("them to an antiques", 69),
                        BookLine("expert to be", 70),
                        BookLine("appraised.", 71),
                        BookLine("", 72),
                        BookLine("They all turned out", 73),
                        BookLine("to be ancient", 74),
                        BookLine("jewellery. The expert", 75),
                        BookLine("put these items into", 76),
                    ),
                ),
                PageSet(
                    Page(
                        BookLine("batches, according to", 55),
                        BookLine("age, and each batch", 56),
                        BookLine("was separated from", 57),
                        BookLine("some 500 years, with", 58),
                        BookLine("the oldest being", 59),
                        BookLine("thousands of years", 60),
                        BookLine("old. The newest set", 61),
                        BookLine("of artefacts was", 62),
                        BookLine("apparently hand", 63),
                        BookLine("crafted by some", 64),
                        BookLine("legendary jeweller", 65),
                    ),
                    Page(
                        BookLine("precisely 450 years", 66),
                        BookLine("ago. From the", 67),
                        BookLine("evidence, I postulate", 68),
                        BookLine("that the phoenix", 69),
                        BookLine("returns to its roost", 70),
                        BookLine("every 500 years for a", 71),
                        BookLine("specific purpose, and", 72),
                        BookLine("I believe this purpose", 73),
                        BookLine("is the key to", 74),
                        BookLine("prolonging its life.", 75),
                        BookLine("", 76),
                    ),
                ),
                PageSet(
                    Page(
                        BookLine("Additionally, from", 55),
                        BookLine("the evidence I deduce", 56),
                        BookLine("that this 500-years", 57),
                        BookLine("cycle is set to repeat", 58),
                        BookLine("50 years from now.", 59),
                        BookLine("", 60),
                        BookLine("The Reborn", 61),
                        BookLine("", 62),
                        BookLine("If you are reading", 63),
                        BookLine("this book, you have no", 64),
                        BookLine("doubt encountered", 65),
                    ),
                    Page(
                        BookLine("the molten, humanoid", 66),
                        BookLine("creatures roaming the", 67),
                        BookLine("caves of the phoenix's", 68),
                        BookLine("lair. These were once", 69),
                        BookLine("adventurers, much like", 70),
                        BookLine("yourself, no doubt,", 71),
                        BookLine("and much like I once", 72),
                        BookLine("was, only less", 73),
                        BookLine("fortunate.", 74),
                        BookLine("These adventurers", 75),
                        BookLine("are those who died", 76),
                    ),
                ),
                PageSet(
                    Page(
                        BookLine("in the phoenix's lair.", 55),
                        BookLine("I imagine they first", 56),
                        BookLine("died in combat with", 57),
                        BookLine("the phoenix itself,", 58),
                        BookLine("and were revived in", 59),
                        BookLine("the flames of the", 60),
                        BookLine("phoenix's power.", 61),
                        BookLine("Subsequent unfortunates,", 62),
                        BookLine("stumbling ill-prepared", 63),
                        BookLine("into the phoenix's", 64),
                        BookLine("lair, will have met", 65),
                    ),
                    Page(
                        BookLine("their end at the", 66),
                        BookLine("hands of these reborn", 67),
                        BookLine("and ultimately joined", 68),
                        BookLine("them when the phoenix", 69),
                        BookLine("returned.", 70),
                        BookLine("", 71),
                        BookLine("These reborn, now", 72),
                        BookLine("in plentiful number,", 73),
                        BookLine("serve to protect the", 74),
                        BookLine("lair from who would", 75),
                        BookLine("desecrate it in the", 76),
                    ),
                ),
                PageSet(
                    Page(
                        BookLine("phoenix's absence.", 55),
                        BookLine("I have also witnessed", 56),
                        BookLine("them tending to the", 57),
                        BookLine("eternal trees.", 58),
                        BookLine("", 59),
                        BookLine("The method through", 60),
                        BookLine("which the phoenix", 61),
                        BookLine("revive these men is", 62),
                        BookLine("unknown to me; I", 63),
                        BookLine("witnessed the event", 64),
                        BookLine("only once, from a", 65),
                    ),
                    Page(
                        BookLine("difficult vantage", 66),
                        BookLine("point in order to", 67),
                        BookLine("remain concealed.", 68),
                        BookLine("Some poor fellow", 69),
                        BookLine("chanced upon the", 70),
                        BookLine("cave during a storm,", 71),
                        BookLine("and came inside", 72),
                        BookLine("seeking shelter.", 73),
                        BookLine("He made the grave", 74),
                        BookLine("error of trying to", 75),
                        BookLine("cut down one of the", 76),
                    ),
                ),
                PageSet(
                    Page(
                        BookLine("eternal trees to", 55),
                        BookLine("build a fire.", 56),
                        BookLine("From my hidden", 57),
                        BookLine("vantage point, I", 58),
                        BookLine("could only watch as", 59),
                        BookLine("the reborn set upon", 60),
                        BookLine("him. The battle was", 61),
                        BookLine("not long; the man was", 62),
                        BookLine("outnumbered and", 63),
                        BookLine("outmatched.", 64),
                        BookLine("", 65),
                    ),
                    Page(
                        BookLine("The fallen warrior", 66),
                        BookLine("was taken into the", 67),
                        BookLine("phoenix's roost and", 68),
                        BookLine("placed upon a large", 69),
                        BookLine("stone symbol on the", 70),
                        BookLine("floor. The symbol", 71),
                        BookLine("began to burn, and", 72),
                        BookLine("the phoenix rose up", 73),
                        BookLine("through it, burning", 74),
                        BookLine("the body to ashes.", 75),
                        BookLine("Moments later, the", 76),
                    ),
                ),
                PageSet(
                    Page(
                        BookLine("ashes began to glow", 55),
                        BookLine("white-hot and ebbed", 56),
                        BookLine("and flowed before my", 57),
                        BookLine("very eyes. A short", 58),
                        BookLine("time later, the molten", 59),
                        BookLine("ashes had formed the", 60),
                        BookLine("vague shape of a", 61),
                        BookLine("man.", 62),
                        BookLine("", 63),
                        BookLine("The molten ash", 64),
                        BookLine("creature then defied", 65),
                    ),
                    Page(
                        BookLine("death and rose to its", 66),
                        BookLine("feet. The equipment", 67),
                        BookLine("the adventurer had", 68),
                        BookLine("brought with him was", 69),
                        BookLine("melted down in the", 70),
                        BookLine("cave's natural lava", 71),
                        BookLine("and smithed into a", 72),
                        BookLine("large weapon.", 73),
                        BookLine("This and a set of", 74),
                        BookLine("armour carved from", 75),
                        BookLine("rock was used to", 76),
                    ),
                ),
                PageSet(
                    Page(
                        BookLine("arm him. He then set", 55),
                        BookLine("about he same tasks", 56),
                        BookLine("as the other guardians,", 57),
                        BookLine("with a seemingly innate", 58),
                        BookLine("knowledge of exactly", 59),
                        BookLine("what to do.", 60),
                        BookLine("", 61),
                        BookLine("The magicks behind", 62),
                        BookLine("this completely baffle", 63),
                        BookLine("me. Unfortunately, that", 64),
                        BookLine("is the limit of the", 65),
                    ),
                    Page(
                        BookLine("knowledge of these", 66),
                        BookLine("reborn. All attempt", 67),
                        BookLine("to make contact with", 68),
                        BookLine("them have thus far", 69),
                        BookLine("proved fruitless;", 70),
                        BookLine("they aggressively", 71),
                        BookLine("defend the phoenix's", 72),
                        BookLine("lair from intruders.", 73),
                        BookLine("I have noticed that,", 74),
                        BookLine("at night, they are", 75),
                        BookLine("more relaxed and", 76),
                    ),
                ),
                PageSet(
                    Page(
                        BookLine("passive, requiring", 55),
                        BookLine("more provocation", 56),
                        BookLine("than simply my", 57),
                        BookLine("presence in the", 58),
                        BookLine("cave.", 59),
                        BookLine("", 60),
                        BookLine("Perhaps their", 61),
                        BookLine("activities are linked", 62),
                        BookLine("to the conscious state", 63),
                        BookLine("of the phoenix itself;", 64),
                        BookLine("they could be a kind", 65),
                    ),
                    Page(
                        BookLine("of gestalt entity", 66),
                        BookLine("not several individuals,", 67),
                        BookLine("but parts of a single", 68),
                        BookLine("being? This is just", 69),
                        BookLine("my speculation, but", 70),
                        BookLine("he evidence suggests", 71),
                        BookLine("there is, at the very", 72),
                        BookLine("least, an awareness", 73),
                        BookLine("between the phoenix", 74),
                        BookLine("and its thralls.", 75),
                        BookLine("", 76),
                    ),
                ),
                PageSet(
                    Page(
                        BookLine("The Eternal Trees", 55),
                        BookLine("", 56),
                        BookLine("At varying depths", 57),
                        BookLine("inside the barren", 58),
                        BookLine("and harsh phoenix's", 59),
                        BookLine("lair, I was shocked", 60),
                        BookLine("to find small areas", 61),
                        BookLine("suitable for", 62),
                        BookLine("vegetation.", 63),
                        BookLine("In each of these", 64),
                        BookLine("areas was always", 65),
                    ),
                    Page(
                        BookLine("a tree. During my", 66),
                        BookLine("dwellings into the", 67),
                        BookLine("phoenix's lair, I", 68),
                        BookLine("have thus far come", 69),
                        BookLine("across five different", 70),
                        BookLine("species of tree.", 71),
                        BookLine("I have taken samples", 72),
                        BookLine("of the twigs and had", 73),
                        BookLine("them analysed by an", 74),
                        BookLine("expert in herblore.", 75),
                        BookLine("He tells me they are", 76),
                    ),
                ),
                PageSet(
                    Page(
                        BookLine("of no alchemical value,", 55),
                        BookLine("and are usually burnt", 56),
                        BookLine("purely to release", 57),
                        BookLine("aromas. He identified", 58),
                        BookLine("my samples as having", 59),
                        BookLine("come from the trees", 60),
                        BookLine("cinnamon, sassafras,", 61),
                        BookLine("ailanthus, cedar", 62),
                        BookLine("and mastic.", 63),
                        BookLine("", 64),
                        BookLine("You may well wonder", 65),
                    ),
                    Page(
                        BookLine("why this section is", 66),
                        BookLine("headed 'The ETERNAL", 67),
                        BookLine("Trees' and, dear reader, it", 68),
                        BookLine("is your right to do so. I", 69),
                        BookLine("refer to these trees as", 70),
                        BookLine("eternal due to the fact", 71),
                        BookLine("that, as long as the phoenix", 72),
                        BookLine("lives, these trees will", 73),
                        BookLine("stay inside its lair.", 74),
                    ),
                ),
                PageSet(
                    Page(
                        BookLine("During one of my", 55),
                        BookLine("sojourns into the", 56),
                        BookLine("caves, I came upon a", 57),
                        BookLine("diseased tree. I kept", 58),
                        BookLine("this tree under", 59),
                        BookLine("observation until one", 60),
                        BookLine("of the reborn", 61),
                        BookLine("discovered it. Once it", 62),
                        BookLine("had been discovered,", 63),
                        BookLine("it was but a few days", 64),
                        BookLine("until the phoenix", 65),
                    ),
                    Page(
                        BookLine("returned to its lair", 66),
                        BookLine("to attend the scene;", 67),
                        BookLine("this further enforces", 68),
                        BookLine("the theory of a joint", 69),
                        BookLine("consciousness between", 70),
                        BookLine("the phoenix and its", 71),
                        BookLine("thralls, as the phoenix", 72),
                        BookLine("had no way of knowing", 73),
                        BookLine("this tree was diseased.", 74),
                        BookLine("What I witnessed next", 75),
                        BookLine("was a true show of", 76),
                    ),
                ),
                PageSet(
                    Page(
                        BookLine("this magnificent", 55),
                        BookLine("creature's ingenuity;", 56),
                        BookLine("it burnt the tree to", 57),
                        BookLine("ashes and a fresh", 58),
                        BookLine("sapling was born", 59),
                        BookLine("from the remains.", 60),
                        BookLine("", 61),
                        BookLine("The effort the", 62),
                        BookLine("phoenix goes through", 63),
                        BookLine("to keep these trees", 64),
                        BookLine("close at hand is", 65),
                    ),
                    Page(
                        BookLine("nothing short of", 66),
                        BookLine("remarkable, and it", 67),
                        BookLine("would suggest that", 68),
                        BookLine("they are of great", 69),
                        BookLine("import to the phoenix.", 70),
                        BookLine("", 71),
                        BookLine("I have observed some", 72),
                        BookLine("of the guardians with", 73),
                        BookLine("covered hands, pruning", 74),
                        BookLine("twigs from the trees", 75),
                        BookLine("and working them into a", 76),
                    ),
                ),
                PageSet(
                    Page(
                        BookLine("ribbon of wood with a", 55),
                        BookLine("knife. I have also", 56),
                        BookLine("discovered some large", 57),
                        BookLine("woven baskets in the", 58),
                        BookLine("phoenix's roost. I", 59),
                        BookLine("believe they play a", 60),
                        BookLine("part in some kind of", 61),
                        BookLine("ritual that the phoenix", 62),
                        BookLine("performs, as I", 63),
                        BookLine("discovered the burnt", 64),
                        BookLine("remains of twigs from", 65),
                    ),
                    Page(
                        BookLine("the five eternal trees,", 66),
                        BookLine("near what appears to", 67),
                        BookLine("be the base of a", 68),
                        BookLine("funeral pyre in", 69),
                        BookLine("the roost.", 70),
                        BookLine("", 71),
                        BookLine("Could this ritual be", 72),
                        BookLine("the secret behind the", 73),
                        BookLine("phoenix's seeming", 74),
                        BookLine("immortality?", 75),
                        BookLine("", 76),
                    ),
                ),
                PageSet(
                    Page(
                        BookLine("Could it be that the", 55),
                        BookLine("phoenix returns to", 56),
                        BookLine("its roost to burn", 57),
                        BookLine("to death and be reborn?", 58),
                        BookLine("", 59),
                        BookLine("Is its natural cyclic,", 60),
                        BookLine("rather than eternal?", 61),
                        BookLine("Only time will tell.", 62),
                        BookLine("In five decades,", 63),
                        BookLine("I will return to the", 64),
                        BookLine("lair and observe from", 65),
                    ),
                    Page(
                        BookLine("the shadows whatever", 66),
                        BookLine("it is the phoenix does.", 67),
                        BookLine("In the meantime, I will", 68),
                        BookLine("continue with my", 69),
                        BookLine("research and hope that", 70),
                        BookLine("this book is read and,", 71),
                        BookLine("when that day comes,", 72),
                        BookLine("50 years from the time", 73),
                        BookLine("of writing, I am still", 74),
                        BookLine("fit and well enough to", 75),
                        BookLine("return to this place", 76),
                    ),
                ),
                PageSet(
                    Page(
                        BookLine("and witness the event", 55),
                        BookLine("that occurs once every", 56),
                        BookLine("five centuries.", 57),
                    ),
                ),
            )
    }

    @Suppress("UNUSED_PARAMETER")
    private fun display(
        player: Player,
        pageNum: Int,
        buttonID: Int,
    ): Boolean {
        BookInterface.pageSetup(
            player,
            BookInterface.FANCY_BOOK_3_49,
            TITLE,
            CONTENTS,
        )
        return true
    }

    override fun defineListeners() {
        on(Scenery.SHRINE_41979, IntType.SCENERY, "read-book") { player, _ ->
            BookInterface.openBook(player, BookInterface.FANCY_BOOK_3_49, ::display)
            return@on true
        }
    }
}
