variables:
  MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true -Xmx4g"
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-fast --show-version"

image: maven:3-openjdk-11-slim

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'

before_script:
  - 'free -mh'
  - 'apt-get update -q'

# Cache downloaded dependencies and plugins between builds.
# To keep cache across branches add 'key: "$CI_JOB_NAME"'
cache:
  paths:
    - .m2/repository

verify:jdk11:
  stage: build
  script:
    - 'cd Emulator'
    - 'mvn $MAVEN_CLI_OPTS verify'
  except:
    variables:
      - $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

test:json:
  stage: test
  script:
    - 'apt-get install -q -y --no-install-recommends jq'
    - 'find . -name \*.json -type f -print0 | xargs -0 -n1 -P8 jq empty'
  except:
    variables:
      - $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
