package content.global.plugin.item.book

import content.global.plugin.iface.BookInterface
import content.global.plugin.iface.BookLine
import content.global.plugin.iface.Page
import content.global.plugin.iface.PageSet
import core.game.interaction.IntType
import core.game.interaction.InteractionListener
import core.game.node.entity.player.Player
import shared.consts.Items

class AncientBook : InteractionListener {

    /*
     * The Ancient book is a quest item found during In Aid of the Myreque.
     * After the quest, it is available in the bookcase of a poh,
     * or from the Paterdomus temple.
     *
     * Content match: 14 march 2009
     */

    companion object {
        private const val TITLE = "The Sleeping Seven."
        private val CONTENTS =
            arrayOf(
                PageSet(
                    Page(
                        BookLine("Though little is known of", 55),
                        BookLine("the Fourth age, especially", 56),
                        BookLine("in the land now known as", 57),
                        BookLine("Morytania, some small", 58),
                        BookLine("details of that dark time", 59),
                        BookLine("do yet remain. This work", 60),
                        BookLine("is as complete an account", 61),
                        BookLine("as can be mustered by", 62),
                        BookLine("the author. Its purpose is", 63),
                        BookLine("to straighten the times", 64),
                        BookLine("and tales of those would-", 65),
                    ),
                    Page(
                        BookLine("be heroes buried under", 66),
                        BookLine("Paterdomus.", 67),
                        BookLine("The datum here are", 68),
                        BookLine("vague at best and no", 69),
                        BookLine("truer gauge could be", 70),
                        BookLine("hardly best sought. The", 71),
                        BookLine("least hope of the lowly", 72),
                        BookLine("author herein lies; to", 73),
                        BookLine("recount what small", 74),
                        BookLine("morsels of truth remain", 75),
                        BookLine("in the minds of those that", 76),
                    ),
                ),
                PageSet(
                    Page(
                        BookLine("still live and entreat those", 55),
                        BookLine("very same to paper lest", 56),
                        BookLine("they forever be forgotten.", 57),
                        BookLine("With my rudimentary", 58),
                        BookLine("abilities I prevailed to", 59),
                        BookLine("update the place names of", 60),
                        BookLine("those dark times and", 61),
                        BookLine("instead use those which", 62),
                        BookLine("are in common use so as", 63),
                        BookLine("to give meaning where", 64),
                        BookLine("previously there was", 65),
                    ),
                    Page(
                        BookLine("confusion.", 66),
                        BookLine("", 67),
                        BookLine("Eight centuries and a", 68),
                        BookLine("score into the history of", 69),
                        BookLine("our land there came a", 70),
                        BookLine("darkness which fell about", 71),
                        BookLine("the land once called", 72),
                        BookLine("Hallowvale. The Queen of", 73),
                        BookLine("that sad time, and Iycene", 74),
                        BookLine("of once formidable power,", 75),
                        BookLine("became to be deposed by", 76),

                        ),
                ),
                PageSet(
                    Page(
                        BookLine("'his-dark-self' and his", 55),
                        BookLine("hordes. Against all her", 56),
                        BookLine("considerable will she was", 57),
                        BookLine("forced to kneel and", 58),
                        BookLine("attend 'his-dark-self' in", 59),
                        BookLine("order that she might save", 60),
                        BookLine("her loving husband", 61),
                        BookLine("Ascertes.", 62),
                        BookLine("", 63),
                        BookLine("The darkness which 'his-", 64),
                        BookLine("dark-self' brought with", 65),
                    ),
                    Page(
                        BookLine("him at that time writhed", 66),
                        BookLine("through Hallowvale and", 67),
                        BookLine("wrought its way ever", 68),
                        BookLine("onwards into Misthalin.", 69),
                        BookLine("Though many men did", 70),
                        BookLine("slow its passage to what is", 71),
                        BookLine("now called Varrock, none", 72),
                        BookLine("did manage to halt its", 73),
                        BookLine("progress proper and", 74),
                        BookLine("many brave warriors so", 75),
                        BookLine("employed did die a most", 76),
                    ),
                ),
                PageSet(
                    Page(
                        BookLine("painful and lingering", 55),
                        BookLine("death.", 56),
                        BookLine("", 57),
                        BookLine("Fearing the darkness", 58),
                        BookLine("would sweep Saradomin's", 59),
                        BookLine("glory from the land, some", 60),
                        BookLine("odd collection of priestly", 61),
                        BookLine("advocates and pious", 62),
                        BookLine("followers of brave virtue", 63),
                        BookLine("stood forwards to steel", 64),
                        BookLine("the hearts of the village", 65),
                    ),
                    Page(
                        BookLine("fighters and town militias,", 66),
                        BookLine("the last defence against", 67),
                        BookLine("the evil now fresh from", 68),
                        BookLine("Hallowvale, and from that", 69),
                        BookLine("time till now called", 70),
                        BookLine("Morytania.", 71),
                        BookLine("", 72),
                        BookLine("This collection of priestly", 73),
                        BookLine("valour did cast", 74),
                        BookLine("Saradomin's blessings", 75),
                        BookLine("upon the untrained and", 76),
                    ),
                ),
                PageSet(
                    Page(
                        BookLine("fearful fighters of", 55),
                        BookLine("Varrock and those of her", 56),
                        BookLine("outside villagers. This did", 57),
                        BookLine("raise bravery, courage", 58),
                        BookLine("and righteousness in the", 59),
                        BookLine("hearts of those brave", 60),
                        BookLine("young Misthalanian", 61),
                        BookLine("knights.", 62),
                        BookLine("", 63),
                        BookLine("At long last it came the", 64),
                        BookLine("time that the rabble of the", 65),
                    ),
                    Page(
                        BookLine("Misthalin defence started", 66),
                        BookLine("to bite and the tide of evil", 67),
                        BookLine("from Morytania became", 68),
                        BookLine("smashed and torn on", 69),
                        BookLine("their pikes and staves. All", 70),
                        BookLine("caught courage from the", 71),
                        BookLine("seven priestly warriors", 72),
                        BookLine("whose names shall be", 73),
                        BookLine("disgorged forthwith.", 74),
                        BookLine("", 75),
                        BookLine("1: Iriandul Caistlyn - A", 76),
                    ),
                ),
                PageSet(
                    Page(
                        BookLine("true leader of the holy", 55),
                        BookLine("seven, though rarely ever", 56),
                        BookLine("a footfall in front of", 57),
                        BookLine("Ivandis, who was ever", 58),
                        BookLine("eager to smash the evil", 59),
                        BookLine("and force the tide back", 60),
                        BookLine("into Morytania.", 61),
                        BookLine("", 62),
                        BookLine("2: Sarl Dunegun of", 63),
                        BookLine("Edgeville - A pious yet", 64),
                        BookLine("brutal man. When", 65),
                    ),
                    Page(
                        BookLine("wielding his mace he led", 66),
                        BookLine("many fighters on", 67),
                        BookLine("skirmishes to keep the evil", 68),
                        BookLine("from spreading and", 69),
                        BookLine("outflanking the group.", 70),
                        BookLine("", 71),
                        BookLine("3: Friar Twiblick of", 72),
                        BookLine("Taverley - A devout man", 73),
                        BookLine("of worship whose brave", 74),
                        BookLine("talks and uncommon", 75),
                        BookLine("speeches raised the spirits", 76),
                    ),
                ),
                PageSet(
                    Page(
                        BookLine("and abilities of men above", 55),
                        BookLine("that of mortals so they", 56),
                        BookLine("fought as though Guthix", 57),
                        BookLine("himself were at their side,", 58),
                        BookLine("redressing the balance", 59),
                        BookLine("that 'his-dark-self' has", 60),
                        BookLine("spoilt.", 61),
                        BookLine("", 62),
                        BookLine("4: Derygull Templeton of", 63),
                        BookLine("Falador - A great oak of", 64),
                        BookLine("a man, so well imbued", 65),
                    ),
                    Page(
                        BookLine("with Saradomin's will and", 66),
                        BookLine("martial ability that he fair", 67),
                        BookLine("commanded people's", 68),
                        BookLine("respect and admiration", 69),
                        BookLine("and they eagerly followed", 70),
                        BookLine("him into battle. His", 71),
                        BookLine("booming voice rallied man", 72),
                        BookLine("in times of fierce fighting,", 73),
                        BookLine("this allowing them to", 74),
                        BookLine("regroup and focus their", 75),
                        BookLine("brutal, savage violence", 76),
                    ),
                ),
                PageSet(
                    Page(
                        BookLine("and force capitulation", 55),
                        BookLine("from writhing,", 56),
                        BookLine("cowardly, evil hordes.", 57),
                        BookLine("", 58),
                        BookLine("5: Ivandis Seergaze of", 59),
                        BookLine("Lumbridge - A daft and", 60),
                        BookLine("well skilled man of", 61),
                        BookLine("unusual appearance, he", 62),
                        BookLine("held a most bizarre", 63),
                        BookLine("control over some", 64),
                        BookLine("powerful minions of", 65),
                    ),
                    Page(

                        BookLine("Drakan's horde. A rod or", 66),
                        BookLine("staff helped imbue him", 67),
                        BookLine("with such power. Then", 68),
                        BookLine("with the aide of a Guthix", 69),
                        BookLine("serum he would turn the", 70),
                        BookLine("vile entity, often times", 71),
                        BookLine("destroying the creature", 72),
                        BookLine("instantly or reverting it", 73),
                        BookLine("to an original incarnation", 74),
                        BookLine("or worst of all enraging it", 75),
                        BookLine("greatly, much to the", 76),
                    ),
                ),
                PageSet(
                    Page(
                        BookLine("chagrin of his holy", 55),
                        BookLine("brothers.", 56),
                        BookLine("", 57),
                        BookLine("6: Erysail the Pious of", 58),
                        BookLine("Rimmington - A woman", 59),
                        BookLine("of such noble and just", 60),
                        BookLine("nature that she", 61),
                        BookLine("commanded the will of the", 62),
                        BookLine("Misthalanian fighters high", 63),
                        BookLine("and right, ever at the", 64),
                        BookLine("front of battle displaying", 65),
                    ),
                    Page(
                        BookLine("courage and aiding those", 66),
                        BookLine("in need.", 67),
                        BookLine("", 68),
                        BookLine("7: Essiandar Gar of", 69),
                        BookLine("Draynor - A fearless", 70),
                        BookLine("woman at even such a", 71),
                        BookLine("worthy age. It was said", 72),
                        BookLine("that her indignation at the", 73),
                        BookLine("evil scourge was enough", 74),
                        BookLine("to make the most", 75),
                        BookLine("cowardly of men in her", 76),
                    ),
                ),
                PageSet(
                    Page(
                        BookLine("ranks act like lions in the", 55),
                        BookLine("fiercest fighting.", 56),
                        BookLine("", 57),
                        BookLine("And with these seven", 58),
                        BookLine("priestly warriors all", 59),
                        BookLine("together committed to this", 60),
                        BookLine("act, they brought the", 61),
                        BookLine("furious intent of", 62),
                        BookLine("Saradomin's will and", 63),
                        BookLine("forced the evil tide from", 64),
                        BookLine("Morytania back into those", 65),
                    ),
                    Page(
                        BookLine("very same dark lands.", 66),
                        BookLine("The fighting became", 67),
                        BookLine("fiercest at Silvarea and", 68),
                        BookLine("they stood side by side to", 69),
                        BookLine("prevent the evil from", 70),
                        BookLine("entering Misthalin again.", 71),
                        BookLine("", 72),
                        BookLine("The very spot where", 73),
                        BookLine("Paterdomus now stands", 74),
                        BookLine("is near the final battle", 75),
                        BookLine("ground for the saving of", 76),
                    ),
                ),
                PageSet(
                    Page(
                        BookLine("Misthalin. The temple", 55),
                        BookLine("stands even now as a", 56),
                        BookLine("contentious reminder to", 57),
                        BookLine("those evil minions who", 58),
                        BookLine("would seek to wreak", 59),
                        BookLine("havoc in the land of", 60),
                        BookLine("Saradomin. As the priestly", 61),
                        BookLine("brothers and sisters", 62),
                        BookLine("fought on, some of them", 63),
                        BookLine("cast blessings into the", 64),
                        BookLine("Salve and sealed it in the", 65),
                    ),
                    Page(
                        BookLine("vengeful power of", 66),
                        BookLine("Saradomin who would act", 67),
                        BookLine("as Misthalin's guardian", 68),
                        BookLine("against 'his-dark-self'.", 69),
                        BookLine("", 70),
                        BookLine("Upon this foundation of", 71),
                        BookLine("holy power Paterdomus", 72),
                        BookLine("was built. Within its holy", 73),
                        BookLine("eminence the saintly", 74),
                        BookLine("remains of those seven", 75),
                        BookLine("priestly warriors, it is", 76),
                    ),
                ),
                PageSet(
                    Page(
                        BookLine("believed, now rest,", 55),
                        BookLine("though there is sometimes", 56),
                        BookLine("discord about one such", 57),
                        BookLine("burial. It was through", 58),
                        BookLine("happenstance that the", 59),
                        BookLine("author became aware of a", 60),
                        BookLine("document which I shall", 61),
                        BookLine("herein duplicate without", 62),
                        BookLine("any additions or", 63),
                        BookLine("omissions. It is said to be", 64),
                        BookLine("written by the brothers in", 65),
                    ),
                    Page(
                        BookLine("arms of Ivandis Seergaze,", 66),
                        BookLine("the ever eager:", 67),
                        BookLine("", 68),
                        BookLine("'The resting place of", 69),
                        BookLine("Ivandis Seergaze of", 70),
                        BookLine("Lumbridge is easily", 71),
                        BookLine("missed for its simpleness", 72),
                        BookLine("and trivial appearance. In", 73),
                        BookLine("the midst of Mort Myre", 74),
                        BookLine("lies a long cavern", 75),
                        BookLine("running from North", 76),
                    ),
                ),
                PageSet(
                    Page(
                        BookLine("West to South East, with", 55),
                        BookLine("three caverns along the", 56),
                        BookLine("South Western wall and", 57),
                        BookLine("two caverns on the North", 58),
                        BookLine("Eastern. Ivandis was put", 59),
                        BookLine("to rest in the smaller o", 60),
                        BookLine("the two caverns along the", 61),
                        BookLine("North Eastern wall with", 62),
                        BookLine("his worldly possessions.", 63),
                        BookLine("Appropriate preparations", 64),
                        BookLine("were made to ensure the", 65),
                    ),
                    Page(
                        BookLine("safety of his mortal", 66),
                        BookLine("remains and the cavern", 67),
                        BookLine("that formed his tomb was", 68),
                        BookLine("sealed up with boards. I,", 69),
                        BookLine("Keorgius Feryis, along", 70),
                        BookLine("with his many other", 71),
                        BookLine("brothers in arms did", 72),
                        BookLine("score marks into the sides", 73),
                        BookLine("of the wall next to the", 74),
                        BookLine("cavern in order to mark", 75),
                        BookLine("it out for later recovery", 76),
                    ),
                ),
                PageSet(
                    Page(
                        BookLine("and to deter possible", 55),
                        BookLine("intruders by making the", 56),
                        BookLine("marks look like those of", 57),
                        BookLine("some fearsome beast.'", 58),
                        BookLine("", 59),
                        BookLine("Though I have made but", 60),
                        BookLine("preliminary and", 61),
                        BookLine("trepidatious journeys into", 62),
                        BookLine("Morytania thus far, the", 63),
                        BookLine("'proposed' location of", 64),
                        BookLine("Ivandis' primitive tomb", 65),
                    ),
                    Page(
                        BookLine("has evaded me. It is with", 66),
                        BookLine("the author's most delicate", 67),
                        BookLine("and humble of", 68),
                        BookLine("suggestions that this", 69),
                        BookLine("'primitive' tomb be cast", 70),
                        BookLine("from the reader's mind as", 71),
                        BookLine("it is, in all likelihood, a", 72),
                        BookLine("trap made by evil minions", 73),
                        BookLine("to beguile the unwary", 74),
                        BookLine("into Morytania.", 75),
                    ),
                ),
            )
    }

    @Suppress("UNUSED_PARAMETER")
    private fun display(player: Player, pageNum: Int, buttonID: Int): Boolean {
        BookInterface.pageSetup(player, BookInterface.FANCY_BOOK_3_49, TITLE, CONTENTS)
        return true
    }

    override fun defineListeners() {
        on(Items.ANCIENT_BOOK_7633, IntType.ITEM, "read") { player, _ ->
            BookInterface.openBook(player, BookInterface.FANCY_BOOK_3_49, ::display)
            return@on true
        }
    }
}
