package content.global.handlers.npc

import core.game.node.entity.npc.AbstractNPC
import core.game.world.map.Location
import core.plugin.Initializable
import org.rs.consts.NPCs

@Initializable
class ShopNPC(
    id: Int = 0,
    location: Location? = null,
) : AbstractNPC(id, location) {
    override fun construct(
        id: Int,
        location: Location,
        vararg objects: Any,
    ): AbstractNPC {
        return ShopNPC(id, location)
    }

    override fun getIds(): IntArray {
        return ID
    }

    override fun init() {
        super.init()
        isWalks = true
    }

    override fun getWalkRadius(): Int {
        return 3
    }

    companion object {
        private val ID =
            intArrayOf(
                NPCs.LIZARD_MAN_70,
                NPCs.NULODION_209,
                NPCs.GUARD_297,
                NPCs.MAGIC_STORE_OWNER_461,
                NPCs.VALAINE_536,
                NPCs.GEM_TRADER_540,
                NPCs.ZEKE_541,
                NPCs.LOUIE_LEGS_542,
                NPCs.KARIM_543,
                NPCs.RANAEL_544,
                NPCs.DOMMIK_545,
                NPCs.ZAFF_546,
                NPCs.HORVIK_549,
                NPCs.SHOP_ASSISTANT_552,
                NPCs.AUBURY_553,
                NPCs.FANCY_DRESS_SHOP_OWNER_554,
                NPCs.GRUM_556,
                NPCs.WYDIN_557,
                NPCs.GERRANT_558,
                NPCs.CANDLE_MAKER_562,
                NPCs.JUKAT_564,
                NPCs.SILVER_MERCHANT_569,
                NPCs.GEM_MERCHANT_570,
                NPCs.BAKER_571,
                NPCs.SPICE_SELLER_572,
                NPCs.FUR_TRADER_573,
                NPCs.HARRY_576,
                NPCs.DROGO_DWARF_579,
                NPCs.FLYNN_580,
                NPCs.WAYNE_581,
                NPCs.DWARF_582,
                NPCs.HERQUIN_584,
                NPCs.ROMMIK_585,
                NPCs.GAIUS_586,
                NPCs.JATIX_587,
                NPCs.ZENESHA_589,
                NPCs.FRENITA_593,
                NPCs.NURMOF_594,
                NPCs.TEA_SELLER_595,
                NPCs.HUDO_600,
                NPCs.ROMETTI_601,
                NPCs.GULLUCK_602,
                NPCs.SQUIRE_606,
                NPCs.TRIBAL_WEAPON_SALESMAN_692,
                NPCs.FISHERMAN_704,
                NPCs.ALFONSE_THE_WAITER_793,
                NPCs.HELEMOS_797,
                NPCs.LUNDAIL_903,
                NPCs.RUFUS_1038,
                NPCs.BARKER_1039,
                NPCs.TOSTIG_1079,
                NPCs.TAMAYU_1167,
                NPCs.QUARTERMASTER_1208,
                NPCs.YRSA_1301,
                NPCs.SKULGRIMEN_1303,
                NPCs.SOLIHIB_1433,
                NPCs.DAGA_1434,
                NPCs.TUTAB_1435,
                NPCs.SANIBOCH_1596,
                NPCs.VANNAKA_1597,
                NPCs.CHAELDAR_1598,
                NPCs.CHAELDAR_1599,
                NPCs.RICHARD_1783,
                NPCs.ALI_MORRISANE_1862,
                NPCs.ALI_THE_KEBAB_SELLER_1865,
                NPCs.EMBALMER_1980,
                NPCs.VIGR_2151,
                NPCs.SANTIRI_2152,
                NPCs.HERVI_2157,
                NPCs.TATI_2160,
                NPCs.AGMUNDI_2161,
                NPCs.VERMUNDI_2162,
                NPCs.KJUT_2198,
                NPCs.OLIVIA_2233,
                NPCs.MAGE_OF_ZAMORAK_2259,
                NPCs.SARAH_2304,
                NPCs.VANESSA_2305,
                NPCs.ALICE_2307,
                NPCs.ORONWEN_2353,
                NPCs.OLIVIA_2572,
                NPCs.TZHAAR_HUR_TEL_2620,
                NPCs.TZHAAR_MEJ_ROH_2623,
                NPCs.SEDDU_3038,
                NPCs.ENTRANCE_GUARDIAN_3097,
                NPCs.SMITH_3162,
                NPCs.MIKE_3166,
                NPCs.ROMILY_WEAKLAX_3205,
                NPCs.SAWMILL_OPERATOR_4250,
                NPCs.LIDIO_4293,
                NPCs.LILLY_4294,
                NPCs.BABA_YAGA_4513,
                NPCs.ARTIMEUS_5109,
                NPCs.ALECK_5110,
                NPCs.URBI_5266,
                NPCs.JAMILA_5268,
                NPCs.RAUM_URDA_STEIN_5485,
                NPCs.SKULI_MYRKA_5486,
                NPCs.KEEPA_KETTILON_5487,
                NPCs.PET_SHOP_OWNER_6750,
                NPCs.PET_SHOP_OWNER_6893,
                NPCs.PET_SHOP_OWNER_6898,
                NPCs.DRUIDESS_6988,
                NPCs.CHARGURR_7053,
                NPCs.AEMAD_590,
                NPCs.ARHEIN_563,
                NPCs.ARMOUR_SALESMAN_682,
                NPCs.AUREL_3541,
                NPCs.AUREL_7396,
                NPCs.BANDIT_SHOPKEEPER_1917,
                NPCs.BOB_519,
                NPCs.BOLKOY_471,
                NPCs.BOW_AND_ARROW_SALESMAN_683,
                NPCs.BRIAN_559,
                NPCs.BRIAN_1860,
                NPCs.CHADWELL_971,
                NPCs.DALLDAV_2356,
                NPCs.DAVON_588,
                NPCs.DWARF_582,
                NPCs.EUDAV_2352,
                NPCs.FAIRY_SHOPKEEPER_534,
                NPCs.FIDELIO_1040,
                NPCs.FINN_3922,
                NPCs.GUNSLIK_2154,
                NPCs.HICKTON_575,
                NPCs.HIRKO_4558,
                NPCs.HOLOY_4559,
                NPCs.HURA_4563,
                NPCs.IFABA_1436,
                NPCs.JIMINUA_560,
                NPCs.JOSSIK_1334,
                NPCs.KAZGAR_2086,
                NPCs.KORTAN_591,
                NPCs.LOWE_550,
                NPCs.LURGON_5798,
                NPCs.MARKET_SELLER_1866,
                NPCs.MELANA_MOONLANDER_4516,
                NPCs.MYSTERIOUS_OLD_MAN_410,
                NPCs.NOTERAZZO_597,
                NPCs.OBLI_516,
                NPCs.OGRE_TRADER_873,
                NPCs.RAZMIRE_KEELGAN_1254,
                NPCs.SHANTAY_836,
                NPCs.SHOPKEEPER_520,
                NPCs.SHOPKEEPER_522,
                NPCs.SHOPKEEPER_522,
                NPCs.SHOPKEEPER_524,
                NPCs.SHOPKEEPER_526,
                NPCs.SHOPKEEPER_528,
                NPCs.SHOPKEEPER_530,
                NPCs.SHOPKEEPER_532,
                NPCs.SHOPKEEPER_551,
                NPCs.SHOP_ASSISTANT_521,
                NPCs.SHOP_ASSISTANT_523,
                NPCs.SHOP_ASSISTANT_525,
                NPCs.SHOP_ASSISTANT_529,
                NPCs.SHOP_ASSISTANT_531,
                NPCs.SHOP_ASSISTANT_533,
                NPCs.TRADER_CREWMEMBER_4651,
                NPCs.TRADER_CREWMEMBER_4652,
                NPCs.TRADER_CREWMEMBER_4653,
                NPCs.TRADER_CREWMEMBER_4654,
                NPCs.TRADER_CREWMEMBER_4655,
                NPCs.TRADER_CREWMEMBER_4656,
                NPCs.TRADER_STAN_4650,
                NPCs.TRADER_SVEN_4716,
                NPCs.WISTAN_1083,
                NPCs.ZAMBO_568,
            )
    }
}
