// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Management.proto

package proto.management;

/**
 * The interface Clan settings update or builder.
 */
public interface ClanSettingsUpdateOrBuilder extends
    // @@protoc_insertion_point(interface_extends:management.ClanSettingsUpdate)
    com.google.protobuf.MessageOrBuilder {
}
