package content.global.activity.ttrail

enum class PuzzleBox(
    val anagram: String,
    val solution: String,
    val location: String,
    val challenge: String?,
) {
    A_BAS("A Bas", "Saba", "In a cave near Burthorpe, north of the Warriors' Guild", null),
    A_ZEN_SHE(
        "A Zen She",
        "Zenesha",
        "The Platebody shop on the Southern edge of Ardougne centre square",
        "Puzzle Box",
    ),
    ACE_MATCH_ELM(
        "Ace Match Elm",
        "Cam The Camel",
        "Just outside the gates of the Duel Arena, Camulet not required",
        "Puzzle Box",
    ),
    AHA_JAR("Aha Jar", "Jaraah", "The hospital of the Duel Arena", null),
    AN_PAINT_TONIC("An Paint Tonic", "Captain Ninto", "In the bar under White Wolf Mountain", "Puzzle Box"),
    ARC_O_LINE(
        "Arc O Line",
        "Caroline",
        "North Witchaven next to the row boat. After Sea Slug Quest is found upstairs in house East of Dungeon entrance.",
        "11",
    ),
    ARE_COL("Are Col", "Oracle", "The peak of Ice Mountain West of Edgeville", "48"),
    ARR_SO_I_AM_A_CRUST(
        "Arr! So I am a crust, and?",
        "Ramara du Croissant",
        "In the forge in Piscatoris Fishing Colony",
        "Puzzle Box",
    ),
    BAIL_TRIMS("Bail Trims", "Brimstail", "In the cave West of the South bank in Gnome Stronghold", null),
    BY_LOOK("By Look", "Bolkoy", "In the Tree Gnome Village general store", "13"),
    C_ON_GAME_HOC("C on game hoc", "Gnome Coach", "Walking around the Gnome Ball course West of the Grand Tree", "6"),
    DT_RUN_B("Dt Run B", "Brundt", "Longhall in the centre of Rellekka", "4"),
    EEK_ZERO_OP(
        "Eek Zero Op",
        "Zookeeper",
        "Ardougne zoo",
        "40, +1 if Eagles Peak is completed, +1 if Hunt for Red Raktuber is completed",
    ),
    EL_OW("El Ow", "Lowe", "Varrock archery store", null),
    ERR_CURE_IT("Err Cure It", "Recruiter", "West Ardougne centre square", "20"),
    GOBLIN_KERN("Goblin Kern", "King Bolren", "Tree Gnome Village, next to the Spirit Tree", null),
    GOT_A_BOY("Got A Boy", "Gabooty", "Centre of Tai Bwo Wannai", "11"),
    GULAG_RUN("Gulag Run", "Uglug Nar", "In Jiggig, just South of the Castle Wars lobby", "Puzzle Box"),
    HALT_US("Halt Us", "Luthas", "Musa Point banana plantation", "33"),
    HE_DO_POSE("He Do Pose. It Is Cultrrl, Mk?", "Riki the sculptor's model", "East side of Keldagrim", "Puzzle Box"),
    ICY_FE("Icy Fe", "Fycie", "Rantz's cave, South-east of Gu'Tanoth", null),
    I_EAT_ITS_CHART_HINTS_DO_U(
        "I Eat Its Chart Hints Do U",
        "Shiratti the Custodian",
        "North of the fountain in Nardah",
        "Puzzle Box",
    ),
    I_FAFFY_RUN(
        "I Faffy Run",
        "Fairy Nuff",
        "Before A Fairy Tale Part II she is in the room north of the bank in Zanaris, after, however, players must get the certificate from the potion shelf and use the fairy rings in this order \"AIR\", \"DLR\", \"DJQ\", \"AJS\"",
        "Puzzle Box",
    ),
    LAND_DOOMD("Land Doomd", "Odd Old Man", "The Limestone mine between Varrock and Paterdomus", "Puzzle Box"),
    LARK_IN_DOG("Lark In Dog", "King Roald", "First floor of Varrock castle", "24"),
    ME_AM_THE_CALC(
        "Me Am The Calc",
        "Cam the Camel",
        "Just outside the gates of the Duel Arena, Camulet not required",
        "Puzzle Box",
    ),
    ME_IF("Me if", "Femi", "Just outside the gates of Tree Gnome Stronghold", null),
    NOD_MED("Nod med", "Edmond", "North of Ardougne Castle, due West of the Northern bank", "3"),
    O_BIRDZ_A_ZANY_EN_PC(
        "O Birdz A Zany En Pc",
        "Cap'n Izzy no Beard",
        "The Agility Arena entrance in Brimhaven",
        "33",
    ),
    OK_CO("Ok Co", "Cook", "Ground floor of Lumbridge Castle", "9"),
    OR_ZINC_FUMES_WARD(
        "Or Zinc Fumes Ward",
        "Wizard Frumscone",
        "Downstairs in the Mage Guild (need 66 magic to enter)",
        "Puzzle Box",
    ),
    PEATY_PERT("Peaty Pert", "Party Pete", "Party Hall in Falador", null),
    PROFS_LOSE_WRONG_PIE("Profs Lose Wrong Pie", "Professor Onglewip", "Wizards Tower South of Draynor", "Puzzle Box"),
    R_AK_MI("R Ak Mi", "Karim", "Al Kharid Kebab shop just South of the furnace", "5"),
    RED_ART_TANS("Red Art Tans", "Trader Stan", "Port Sarim Charter ship", "Puzzle Box"),
    SEQUIN_DIRGE(
        "Sequin Dirge",
        "Queen Sigrid",
        "Second floor of the Etceteria castle, after Blood Runs Deep quest she is in Miscellania throne room",
        "Puzzle Box",
    ),
    SNAH("Snah", "Hans", "Lumbridge Castle courtyard", null),
    THEM_CALL_CAME(
        "Them Call Came",
        "Cam the camel",
        "Just outside the gates of the Duel Arena, Camulet not required",
        "Puzzle Box",
    ),
}
