package content.region.kandarin.quest.phoenix.handlers

import content.global.handlers.iface.BookInterface
import content.global.handlers.iface.BookLine
import content.global.handlers.iface.Page
import content.global.handlers.iface.PageSet
import core.game.interaction.IntType
import core.game.interaction.InteractionListener
import core.game.node.entity.player.Player
import org.rs.consts.Scenery

class PhoenixBook : InteractionListener {
    companion object {
        private const val TITLE = "The Phoenix"
        private val CONTENTS =
            arrayOf(
                PageSet(
                    Page(
                        BookLine("~ Foreword ~", 55),
                        BookLine("", 56),
                        BookLine("I have devoted much of my life", 57),
                        BookLine("to the study of this wondrous", 58),
                        BookLine("creature: the firebird of legend,", 59),
                        BookLine("the phoenix.", 60),
                        BookLine("", 61),
                        BookLine("I placed this book and the shrine", 62),
                        BookLine("it rests on in the phoenix's roost,", 63),
                        BookLine("shortly after it departed on one of", 64),
                        BookLine("its many long absences from its lair.", 65),
                    ),
                    Page(
                        BookLine("I will no doubt be continuing", 66),
                        BookLine("my research until the phoenix", 67),
                        BookLine("returns for its rebirth.", 68),
                        BookLine("Unfortunately,based on my research,", 69),
                        BookLine("this event will not occur until", 70),
                        BookLine("I am fully five decades older,", 71),
                        BookLine("and will no doubt have became a", 72),
                        BookLine("frail old man, unable to travel", 73),
                        BookLine("and see the event I have waited", 74),
                        BookLine("a lifetime to witness.", 75),
                    ),
                ),
                PageSet(
                    Page(
                        BookLine("I leave these records of my", 55),
                        BookLine("findings inside the phoenix's", 56),
                        BookLine("lair in the fond hope that you,", 57),
                        BookLine("dear reader, will read them, and", 58),
                        BookLine("come to understand and admire", 59),
                        BookLine("the phoenix as I do and will all", 60),
                        BookLine("my life.", 61),
                        BookLine("", 62),
                        BookLine("Strength through balance,", 63),
                        BookLine("Brian Twitcher.", 64),
                    ),
                    Page(
                        BookLine(" ~ The Phoenix ~", 66),
                        BookLine("The phoenix is a large avian creature.", 67),
                        BookLine("In terms of physical appearance,", 68),
                        BookLine("it is similar to a very large", 69),
                        BookLine("eagle, only with fiery feathers", 70),
                        BookLine("almost all over, and a crest atop", 71),
                        BookLine("its head. The only part of it", 72),
                        BookLine("that is not fiery oranges and", 73),
                        BookLine("reds is its tail - its long,", 74),
                        BookLine("beautiful tail.", 75),
                    ),
                ),
                PageSet(
                    Page(
                        BookLine("The magnificent tail feathers", 55),
                        BookLine("are a burning red toward the base,", 56),
                        BookLine("and the colours grow gradually", 57),
                        BookLine("cooler towards the tips of the", 58),
                        BookLine("feathers, flowing from red to", 59),
                        BookLine("orange to yellow to green to a", 60),
                        BookLine("cool blue. The phoenix is truly", 61),
                        BookLine("a magnificent sight to behold.", 62),
                    ),
                    Page(
                        BookLine("My knowledge of the creature is", 66),
                        BookLine("little more than observations of", 67),
                        BookLine("its behaviour; I kept myself", 68),
                        BookLine("concealed during my research,", 69),
                        BookLine("partially to avoid startling or", 70),
                        BookLine("upsetting the phoenix, but mostly", 71),
                        BookLine("out of a human fear of death after", 72),
                        BookLine("witnessing some of its powerful", 73),
                        BookLine("magicks. The phoenix spends most", 74),
                        BookLine("of its time away from its lair", 75),
                    ),
                ),
                PageSet(
                    Page(
                        BookLine("(one of the main reasons I have", 55),
                        BookLine("been able to examine its roost", 56),
                        BookLine("chamber as much as I have!)", 57),
                        BookLine("and seems to return when there", 58),
                        BookLine("is an abnormal occurrence or", 59),
                        BookLine("problem within the lair.", 60),
                        BookLine("", 61),
                        BookLine("I have a theory as to how", 62),
                        BookLine("the phoenix does this, and", 63),
                        BookLine("I shall explain later in this", 64),
                        BookLine("book. The phoenix's magicks include", 65),
                    ),
                    Page(
                        BookLine("the incomprehensible ability to", 66),
                        BookLine("revive the dead.", 67),
                        BookLine("Creatures it revives became servants", 68),
                        BookLine("to the phoenix, and spend their days", 69),
                        BookLine("in its lair. These are described in", 70),
                        BookLine("the next section, 'The Reborn'. ", 71),
                        BookLine("", 72),
                        BookLine("The magic it has over life and death,", 73),
                        BookLine("coupled with evidence 'liberated',", 74),
                        BookLine("from the phoenix's roost, lead me to", 75),
                    ),
                ),
                PageSet(
                    Page(
                        BookLine("believe that the phoenix is an", 55),
                        BookLine("ancient creature to whom the laws", 56),
                        BookLine("of life and death do not apply. I", 57),
                        BookLine("discovered several items in the", 58),
                        BookLine("phoenix's roost that looked out", 59),
                        BookLine("of place, and took them to an", 60),
                        BookLine("antiques expert to be appraised.", 61),
                        BookLine("They all turned out to be ancient", 62),
                        BookLine("jewellery.", 63),
                    ),
                    Page(
                        BookLine("The expert put these items into", 66),
                        BookLine("batches, according to age, and", 67),
                        BookLine("each batch was separated by some", 68),
                        BookLine("500 years, with the oldest being", 69),
                        BookLine("thousands of years old. The newest", 70),
                        BookLine("set of artefacts was apparently", 71),
                        BookLine("hand-crafted by some legendary", 72),
                        BookLine("jeweller precisely 450 years ago.", 73),
                        BookLine("From the evidence, I postulate", 74),
                        BookLine("that the phoenix returns to its", 75),
                    ),
                ),
                PageSet(
                    Page(
                        BookLine("roost every 500 years for a specific", 55),
                        BookLine("purpose, and I believe this purpose", 56),
                        BookLine("is the key to prolonging its life.", 57),
                        BookLine("", 58),
                        BookLine("Additionally, from the evidence,", 59),
                        BookLine("I deduce that this 500-year cycle", 60),
                        BookLine("is set to repeat 50 years from now.", 61),
                        BookLine("", 62),
                        BookLine(" ~ The Reborn ~", 63),
                        BookLine("", 64),
                        BookLine("If you are reading this book,", 65),
                    ),
                    Page(
                        BookLine("you have no doubt encountered", 66),
                        BookLine("the molten, humanoid creatures", 67),
                        BookLine("roaming the caves of the phoenix's", 68),
                        BookLine("lair. These were once adventurers,", 69),
                        BookLine("much like yourself, no doubt,", 70),
                        BookLine("and much like I once was, only", 71),
                        BookLine("less fortunate. These adventurers", 72),
                        BookLine("are those who died in the phoenix's", 73),
                        BookLine("lair. I imagine they first died", 74),
                        BookLine("in combat with the phoenix itself,", 75),
                    ),
                ),
                PageSet(
                    Page(
                        BookLine("and were revived in the flames", 55),
                        BookLine("of the phoenix's power. Subsequent", 56),
                        BookLine("unfortunates, stumbling ill-prepared", 57),
                        BookLine("into the phoenix's lair, will", 58),
                        BookLine("have met their end at the hands", 59),
                        BookLine("of these reborn and ultimately", 60),
                        BookLine("joined them when the phoenix returned.", 61),
                        BookLine("", 62),
                        BookLine("These reborn, now plentiful in", 63),
                        BookLine("number, serve to protect the", 64),
                        BookLine("lair from those who would desecrate", 65),
                    ),
                    Page(
                        BookLine("it in the phoenix's absence.", 66),
                        BookLine("I have also witnessed them tending", 67),
                        BookLine("to the eternal trees.", 68),
                        BookLine("The method through which the", 69),
                        BookLine("phoenix revives these men is", 70),
                        BookLine("unknown to me; I witnessed the", 71),
                        BookLine("event only once, from a difficult", 72),
                        BookLine("vantage point in order to remain", 73),
                        BookLine("concealed.", 74),
                    ),
                ),
                PageSet(
                    Page(
                        BookLine("Some poor fellow chanced upon", 55),
                        BookLine("the cave during a storm, and came", 56),
                        BookLine("inside seeking shelter. He made", 57),
                        BookLine("the grave error of trying to cut", 58),
                        BookLine("down one of the eternal trees", 59),
                        BookLine("to build a fire. From my hidden", 60),
                        BookLine("vantage point, I could only watch", 61),
                        BookLine("as the reborn set upon him. The", 62),
                        BookLine("battle was not long; the man was", 63),
                        BookLine("outnumbered and outmatched. The", 64),
                        BookLine("fallen warrior was taken into", 65),
                    ),
                    Page(
                        BookLine("the phoenix's roost and placed", 66),
                        BookLine("upon a large stone symbol on the", 67),
                        BookLine("floor.", 68),
                        BookLine("", 69),
                        BookLine("The symbol began to burn, and the", 70),
                        BookLine("phoenix rose up through it, burning", 71),
                        BookLine("the body to ashes. Moments later,", 72),
                        BookLine("the ashes began to glow white-hot", 73),
                        BookLine("and ebbed and flowed before my very", 74),
                        BookLine("eyes. A short time later, the molten", 75),
                    ),
                ),
                PageSet(
                    Page(
                        BookLine("ashes had formed the vague shape of", 55),
                        BookLine("a man.", 56),
                        BookLine("", 57),
                        BookLine("The molten ash creature then defied", 58),
                        BookLine("death and rose to its feet.", 59),
                        BookLine("", 60),
                        BookLine("The equipment the adventurer", 61),
                        BookLine("had brought in with him was melted", 62),
                        BookLine("down in the cave's natural lava", 63),
                        BookLine("and smithed into a large weapon.", 64),
                        BookLine("This and a set of armour carved", 65),
                    ),
                    Page(
                        BookLine("from rock was used to arm him.", 66),
                        BookLine("He then set about the same tasks", 67),
                        BookLine("as the other guardians, with a", 68),
                        BookLine("seemingly innate knowledge of", 69),
                        BookLine("exactly what to do. The magicks", 70),
                        BookLine("behind this completely baffle", 71),
                        BookLine("me. Unfortunately, that is the", 72),
                        BookLine("limit of my knowledge of these", 73),
                        BookLine("reborn.", 74),
                    ),
                ),
                PageSet(
                    Page(
                        BookLine("All attempts to make contact", 55),
                        BookLine("with them have thus far proved", 56),
                        BookLine("fruitless; they aggressively defend", 57),
                        BookLine("the phoenix's lair from intruders.", 58),
                        BookLine("I have noticed that, at night,", 59),
                        BookLine("they are more relaxed and passive,", 60),
                        BookLine("requiring more provocation than", 61),
                        BookLine("simply my presence in the cave.", 62),
                        BookLine("", 63),
                        BookLine("Perhaps their activities are linked to", 64),
                        BookLine("the conscious state of the phoenix", 65),
                    ),
                    Page(
                        BookLine("itself; they could be a kind of", 66),
                        BookLine("gestalt entity - not several individuals,", 67),
                        BookLine("but parts of a single being? This", 68),
                        BookLine("is just my speculation, but the", 69),
                        BookLine("evidence suggests there is, at", 70),
                        BookLine("the very least, an awareness between", 71),
                        BookLine("the phoenix and its thralls.", 72),
                    ),
                ),
                PageSet(
                    Page(
                        BookLine("~ The Eternal Trees ~", 55),
                        BookLine("At varying depths inside the", 56),
                        BookLine("barren and harsh phoenix's lair,", 57),
                        BookLine("I was shocked to find small areas", 58),
                        BookLine("suitable for vegetation.", 59),
                        BookLine("In each of these areas was always", 60),
                        BookLine("a tree. During my delvings into", 61),
                        BookLine("the phoenix's lair, I have thus far", 62),
                        BookLine("come across five different species", 63),
                        BookLine("of tree. I have taken samples of the", 64),
                        BookLine("twigs and had them analysed by an", 65),
                    ),
                    Page(
                        BookLine("expert in herblore.", 66),
                        BookLine("", 67),
                        BookLine("He tells me they are of no alchemical", 68),
                        BookLine("value, and are usually burnt purely", 69),
                        BookLine("to release aromas. He identified", 70),
                        BookLine("my samples as having come from", 71),
                        BookLine("the trees cinnamon, sassafras,", 72),
                        BookLine("ailanthus, cedar and mastic. You", 73),
                        BookLine("may well wonder why this section", 74),
                        BookLine("is headed 'The ETERNAL Trees'", 75),
                    ),
                ),
                PageSet(
                    Page(
                        BookLine("and, dear reader, it is your right", 55),
                        BookLine("to do so. I refer to these trees", 56),
                        BookLine("as eternal due to the fact that,", 57),
                        BookLine("as long as the phoenix lives,", 58),
                        BookLine("these trees will stay inside its", 59),
                        BookLine("lair.", 60),
                        BookLine("", 61),
                        BookLine("During one of my sojourns into", 62),
                        BookLine("the caves, I came upon a diseased", 63),
                        BookLine("tree. I kept this tree under", 64),
                        BookLine("observation until one of the reborn", 65),
                    ),
                    Page(
                        BookLine("discovered it.", 66),
                        BookLine("", 67),
                        BookLine("Once it had been discovered, it was", 68),
                        BookLine("but a few days until the phoenix", 69),
                        BookLine("returned to its lair to attend", 70),
                        BookLine("the scene; this further enforces", 71),
                        BookLine("the theory of a joint consciousness", 72),
                        BookLine("between the phoenix and its thralls,", 73),
                        BookLine("as the phoenix had no way of knowing", 74),
                        BookLine("this tree was diseased. What I", 75),
                    ),
                ),
                PageSet(
                    Page(
                        BookLine("witnessed next was a true show", 55),
                        BookLine("of this magnificent creature's", 56),
                        BookLine("ingenuity; it burnt the tree to", 57),
                        BookLine("ashes and a fresh sapling was", 58),
                        BookLine("born from the remains. The effort", 59),
                        BookLine("the phoenix goes through to keep", 60),
                        BookLine("these trees close at hand is", 61),
                        BookLine("nothing short of remarkable,", 62),
                        BookLine("and it would suggest that they are", 63),
                        BookLine("of great import to the phoenix.", 64),
                    ),
                    Page(
                        BookLine("I have observed some of the guardians", 66),
                        BookLine("with covered hands, pruning twigs", 67),
                        BookLine("from the trees and working them", 68),
                        BookLine("into a ribbon of wood with a knife.", 69),
                        BookLine("I have also discovered some large", 70),
                        BookLine("woven baskets in the phoenix's", 71),
                        BookLine("roost. I believe they play a part", 72),
                        BookLine("in some kind of ritual that the", 73),
                        BookLine("phoenix performs, as I discovered", 74),
                        BookLine("the burnt remains of twigs from", 75),
                        BookLine("the five eternal trees, near what", 76),
                    ),
                ),
                PageSet(
                    Page(
                        BookLine("appears to be the base of a funeral", 55),
                        BookLine("pyre in the roost.", 56),
                        BookLine("", 57),
                        BookLine("Could this ritual be the secret", 58),
                        BookLine("behind the phoenix's seeming", 59),
                        BookLine("immortality? Could it be that the", 60),
                        BookLine(" phoenix returns to its roost to", 61),
                        BookLine("burn to death and be reborn?", 62),
                        BookLine("", 63),
                        BookLine("Is its nature cyclic, rather than", 64),
                        BookLine("eternal? Only time will tell.", 65),
                    ),
                    Page(
                        BookLine("In five decades,I will return to", 66),
                        BookLine("the lair and observe from the", 67),
                        BookLine("shadows whatever it is the phoenix", 68),
                        BookLine("does. In the meantime, I will", 69),
                        BookLine("continue with my research and hope", 70),
                        BookLine("that this book is read and, when", 71),
                        BookLine("that day comes, 50 years from the", 72),
                        BookLine("time of writing, I am still fit and", 73),
                        BookLine("well enough to return to this", 74),
                        BookLine("place and witness the event that", 75),
                        BookLine("occurs once every five centuries.", 76),
                    ),
                ),
            )
    }

    @Suppress("UNUSED_PARAMETER")
    private fun display(
        player: Player,
        pageNum: Int,
        buttonID: Int,
    ): Boolean {
        BookInterface.pageSetup(
            player,
            BookInterface.FANCY_BOOK_3_49,
            TITLE,
            CONTENTS,
        )
        return true
    }

    override fun defineListeners() {
        on(Scenery.SHRINE_41979, IntType.SCENERY, "read-book") { player, _ ->
            BookInterface.openBook(player, BookInterface.FANCY_BOOK_3_49, ::display)
            return@on true
        }
    }
}
